// The words of the screens gallery, Arabic first and English equally finished. A key missing in one language is a
// type error.
import { makeWords } from '../../map/words'

export const SCREEN_WORDS = {
  screens: ['الشاشات', 'Screens'],
  lead: ['{s} شاشة يفتحها المستخدم في هذا التطبيق.', '{s} screens a person opens in this app.'],
  leadShots: ['صُوّرت {n} منها، ووُجدت عليها {i} مشكلة استخدام مفتوحة.', '{n} of them are captured, with {i} open usability issues on them.'],
  leadNone: ['لم يجد EAOS شاشات يفتحها المستخدم في هذا المشروع.', 'EAOS found no screens a person opens in this project.'],
  notCaptured: ['لم تُصوَّر الشاشات بعد', 'The screens are not captured yet'],
  notCapturedSub: ['التصوير يشغّل تطبيقك في نسخة منفصلة، فيحتاج موافقتك مرة واحدة. حتى ذلك الحين تظهر هنا كل شاشة بمسارها وملفها.', 'Capturing runs your app in a separate copy, so it needs your agreement once. Until then every screen shows here with its route and its file.'],
  askCapture: ['اطلب من المساعد تشغيل التطبيق وتصوير الشاشات', 'Ask the assistant to run the app and capture the screens'],
  captureRequest: ['شغّل تطبيقي في نسخة منفصلة بأداة run_setup من EAOS، ثم صوّر كل شاشاته.', 'Run my app in a separate copy with the EAOS run_setup tool, then capture every screen.'],
  byStep: ['تأتي بها الخطوة', 'Comes with step'],
  filter: ['أي الشاشات', 'Which screens'],
  filter_all: ['الكل', 'All'],
  filter_issues: ['عليها مشاكل', 'With issues'],
  filter_flagged: ['في رحلتها خلل', 'Journey flags'],
  filter_shot: ['مصوّرة', 'Captured'],
  shown: ['{n} من {t}', '{n} of {t}'],
  none: ['لا شاشة تطابق هذا الاختيار', 'No screen matches'],
  noShot: ['لم تُصوَّر', 'Not captured'],
  notChecked: ['لم تُفحص', 'Not checked'],
  issuesN: ['{n} مشكلة', '{n} issues'],
  noIssues: ['بلا مشاكل', 'No issues'],
  flag_broken_link: ['رابط مكسور', 'Broken link'],
  flag_no_way_in: ['لا رابط يوصل إليها', 'No way in'],
  flag_dead_end: ['طريق مسدود', 'Dead end'],
  flag_duplicate: ['مكررة', 'Duplicate'],
  // detail
  backToList: ['الشاشات', 'Screens'],
  notFound: ['هذه الشاشة ليست في هذا الفحص', 'This screen is not in this check'],
  notFoundSub: ['ربما حُذف مسارها منذ الرابط. افتح معرض الشاشات.', 'Its route may have been removed since the link. Open the screens gallery.'],
  route: ['المسار', 'Route'],
  file: ['ملف الشاشة', 'Screen file'],
  declared: ['معرّفة في', 'Declared in'],
  component: ['المكوّن', 'Component'],
  inJourneys: ['اعرضها في رحلات المستخدم', 'See it in the user journeys'],
  fileFunctions: ['دوال ملفها', 'The functions of its file'],
  viewport: ['عرض الشاشة', 'Viewport'],
  phone: ['هاتف {w}', 'Phone {w}'],
  desktop: ['سطح المكتب {w}', 'Desktop {w}'],
  width: ['{w} بكسل', '{w} px'],
  compare: ['المقارنة', 'Compare'],
  before: ['قبل', 'Before'],
  after: ['بعد', 'After'],
  slider: ['مُنزلق', 'Slider'],
  sliderAria: ['حرّك لتقارن قبل وبعد', 'Move to compare before and after'],
  shotAlt: ['صورة شاشة {r} بعرض {w} بكسل', 'Screen {r} at {w} px'],
  shotMissing: ['هذه الشاشة لم تُصوَّر بعد', 'This screen is not captured yet'],
  issues: ['مشاكل الاستخدام', 'Usability issues'],
  issuesNotChecked: ['لم تُفحص بعد: مشاكل الاستخدام تُفحص على صور الشاشات.', 'Not checked yet: usability issues are checked on the screen shots.'],
  issuesNone: ['لم يجد الفحص مشكلة استخدام على هذه الشاشة.', 'The check found no usability issue on this screen.'],
  fixed: ['أُصلحت', 'Fixed'],
  open: ['مفتوحة', 'Open'],
  openProblem: ['افتح المشكلة', 'Open the problem'],
  pinAria: ['المشكلة {n}: {s}', 'Issue {n}: {s}'],
  inputs: ['حقول الإدخال', 'Input fields'],
  inputsNotMeasured: ['لا يقرأ EAOS حقول الإدخال وتسمياتها بعد.', 'EAOS does not read input fields and their labels yet.'],
  inputsNone: ['لا حقول إدخال في هذه الشاشة.', 'This screen has no input fields.'],
  labelled: ['لها تسمية', 'labelled'],
  unlabelled: ['بلا تسمية', 'no label'],
  required: ['مطلوب', 'required'],
  validated: ['يُتحقق منه', 'validated'],
  sev_critical: ['حرجة', 'Critical'],
  sev_high: ['عالية', 'High'],
  sev_medium: ['متوسطة', 'Medium'],
  sev_low: ['منخفضة', 'Low'],
  sev_info: ['للعلم', 'Info'],
} as const

export type ScreenWord = keyof typeof SCREEN_WORDS
export const useScreenWords = makeWords<ScreenWord>(SCREEN_WORDS)
