// Branch control and scan freshness words (NS46.T18, NS46.T19), Arabic first and English equally finished. Kept apart
// from i18n/catalog.ts like the command centre's words; a key missing in one language is a type error.
import { useWordTable } from '../map/words'

export const BRANCH_WORDS = {
  branches: ['الفروع', 'Branches'],
  branchesLead: ['فروع مشروعك كما يقولها git الآن: أيها مفتوح عندك، وأيها يحلّله الاستوديو، وأي فرع عمل صنعه EAOS لمهمة.',
    'Your project\'s branches as git tells them now: which one is checked out, which one the Studio analyses, and which work branches EAOS made for a task.'],
  // the four branches never mixed up
  checkout: ['المفتوح عندك', 'Your checkout'],
  analysis: ['فرع التحليل', 'Analysis branch'],
  reportOf: ['التقرير لفرع', 'Report is of'],
  base: ['الأساس للمقارنة', 'Compared with'],
  defaultBranch: ['الافتراضي', 'Default'],
  detached: ['HEAD منفصل عند {c}', 'Detached HEAD at {c}'],
  detachedShort: ['HEAD منفصل', 'Detached HEAD'],
  contextDiffers: ['الفرع المفتوح عندك غير فرع التحليل: الاستوديو يحلّل {a} بدون أن يغيّر ما هو مفتوح عندك ({c}).',
    'Your checkout is not the analysis branch: the Studio analyses {a} without changing what you have checked out ({c}).'],
  reportDiffers: ['التقرير المعروض لفرع {r}، وفرع التحليل الآن {a}: أعد الفحص على {a} ليطابقه.',
    'The report shown is of {r}, and the analysis branch is now {a}: re-scan {a} to match it.'],
  // filters and table
  work: ['فروع العمل', 'Work'],
  all: ['كل الفروع', 'All branches'],
  searchBranches: ['ابحث في الفروع', 'Search branches'],
  local: ['محلي', 'Local'],
  remote: ['بعيد {r}', 'Remote {r}'],
  protected: ['محمي', 'Protected'],
  ownerEaos: ['صنعه EAOS', 'Made by EAOS'],
  ownerShared: ['EAOS + آخرون', 'EAOS + others'],
  ownerUnknown: ['المالك غير معروف', 'Owner unknown'],
  aheadBehind: ['متقدّم {a} · متأخر {b}', '{a} ahead · {b} behind'],
  compareUnknown: ['المقارنة غير معروفة', 'Comparison unknown'],
  merged: ['مدموج في {b}', 'Merged into {b}'],
  lastCommit: ['آخر commit', 'Last commit'],
  worktree: ['نسخة عمل', 'Worktree'],
  worktreeHere: ['مفتوح في مجلد مشروعك', 'Checked out in your project folder'],
  worktreeOther: ['مفتوح في نسخة عمل أخرى: {p}', 'Checked out in another worktree: {p}'],
  unsaved: ['{n} تعديل غير محفوظ', '{n} unsaved changes'],
  linkedRuns: ['تشغيلات مرتبطة', 'Linked runs'],
  noBranches: ['ما فيه فروع لعرضها هنا.', 'No branches to show here.'],
  noBranchesWork: ['ما فيه فرع عمل عند EAOS سجل أنه صنعه. الأسماء وحدها ليست دليلًا.', 'No branch EAOS has a record of making. Names alone are not proof.'],
  notGit: ['هذا المجلد ليس مستودع git، فلا فروع لعرضها.', 'This folder is not a git repository, so there are no branches to show.'],
  noOrigin: ['ما فيه مستودع بعيد (origin): الفروع المحلية فقط، وهذا وضع صحيح.', 'There is no remote (origin): local branches only, which is a valid state.'],
  remoteAsOf: ['الفروع البعيدة كما عُرفت آخر مرة: {d}', 'Remote branches as last fetched: {d}'],
  remoteNever: ['الفروع البعيدة كما عُرفت آخر مرة (وقت آخر تحديث غير معروف)', 'Remote branches as last known (last fetch time unknown)'],
  refreshRemote: ['حدّث الفروع البعيدة', 'Refresh remote branches'],
  truncated: ['تُعرض أول {n} فرع فقط.', 'Only the first {n} branches are shown.'],
  missingLinked: ['فروع مرتبطة بتشغيلات ولم تعد موجودة', 'Branches linked to runs that no longer exist'],
  recoverable: ['فروع محذوفة يمكن استرجاعها', 'Deleted branches you can restore'],
  restore: ['استرجع', 'Restore'],
  restoredAs: ['استُرجع باسم {b}', 'Restored as {b}'],
  // the drawer
  details: ['تفاصيل {b}', 'Details of {b}'],
  detailsShort: ['التفاصيل', 'Details'],
  retry: ['أعد المحاولة', 'Try again'],
  sourceCommit: ['الأساس الذي بدأ منه', 'Started from'],
  lineage: ['من أين جاء', 'Lineage'],
  lineageUnknown: ['غير معروف: ما فيه سجل يربط هذا الفرع بأصله، ولا نستنتجه من الاسم.', 'Unknown: no record links this branch to its parent, and it is not guessed from the name.'],
  commitsAhead: ['commits ليست في {b}', 'Commits not in {b}'],
  filesChanged: ['الملفات المتغيرة', 'Changed files'],
  showDiff: ['اعرض الفرق', 'Show the diff'],
  hideDiff: ['أخفِ الفرق', 'Hide the diff'],
  diffCut: ['الفرق طويل: يُعرض أوله فقط.', 'The diff is long: only its start is shown.'],
  checks: ['الفحوص', 'Checks'],
  checksPassed: ['نجحت على هذا الـcommit ({c})', 'Passed on this commit ({c})'],
  checksFailed: ['فشلت على هذا الـcommit ({c})', 'Failed on this commit ({c})'],
  checksNone: ['ما فيه فحوص مسجلة لهذا الـcommit', 'No checks recorded for this commit'],
  destination: ['وجهة الدمج', 'Merge destination'],
  recommended: ['المقترحة: {b}', 'Recommended: {b}'],
  confirmedInto: ['دُمج فعلًا في {b}', 'Actually merged into {b}'],
  notMergedYet: ['ما دُمج بعد', 'Not merged yet'],
  commands: ['الأوامر', 'Commands'],
  blockedBecause: ['غير متاح لأن:', 'Not available because:'],
  // actions
  useForAnalysis: ['حلّل هذا الفرع', 'Analyse this branch'],
  useForAnalysisScan: ['حلّله وأعد الفحص', 'Analyse and re-scan'],
  selectLead: ['يتغيّر ما يحلّله الاستوديو فقط؛ الفرع المفتوح عندك لا يتغيّر.', 'Only what the Studio analyses changes; your checkout does not.'],
  inFlight: ['فيه تشغيل في الانتظار أو يعمل على الفرع الحالي. EAOS لا ينقله لفرع آخر بنفسه: اتركه ينتهي أو أوقفه من صفحة التشغيل، ثم اختر من جديد.',
    'A run is queued or working on the current branch. EAOS never moves it to another branch on its own: let it finish or stop it from Runs, then choose again.'],
  openRuns: ['افتح التشغيل', 'Open runs'],
  mergePreview: ['عاين الدمج', 'Preview the merge'],
  mergeInto: ['ادمج {s} في {t}', 'Merge {s} into {t}'],
  mergePath: ['الطريقة: {p}', 'How: {p}'],
  pathAccept: ['اعتماد دفعة EAOS (يحدّث السجل والتقرير والتقدم مرة واحدة)', 'Accept the EAOS batch (updates the ledger, report and progress once)'],
  pathTransaction: ['دمج محمي بالرؤوس المتوقعة وقفل المشروع', 'A guarded merge at the expected heads, under the project lock'],
  fastForward: ['تقديم مباشر بلا commit دمج', 'Fast-forward, no merge commit'],
  conflicts: ['تعارض في {n} ملف: ما يُدمج شيء، والطرفان يبقيان كما هما.', '{n} file(s) conflict: nothing is merged; both sides stay as they are.'],
  proposeResolution: ['اطلب من مساعدك اقتراح حل', 'Ask your assistant to propose a resolution'],
  uncheckedAck: ['أدمجه بدون فحوص مسجلة لهذا الـcommit', 'I merge it without recorded checks for this commit'],
  confirmMerge: ['أكّد الدمج', 'Confirm the merge'],
  stale: ['تغيّر أحد الفرعين بعد المعاينة: هذه معاينة جديدة، راجعها قبل التأكيد.', 'A branch moved after the preview: this is a new preview, review it before confirming.'],
  deleteLocal: ['احذف الفرع المحلي', 'Delete the local branch'],
  deleteRemote: ['احذف من {r}', 'Delete on {r}'],
  deletePreview: ['ماذا سيحدث عند الحذف', 'What deleting does'],
  deleteMerged: ['كل commits هذا الفرع موجودة في: {b}. لا يضيع شيء، ويُحفظ مرجع للاسترجاع.', 'Every commit of this branch is in: {b}. Nothing is lost, and a recovery ref is kept.'],
  deleteUnmerged: ['{n} commit موجودة في هذا الفرع فقط. تُحفظ في مرجع استرجاع، لكن تأكيدًا ثانيًا مطلوب.', '{n} commit(s) exist only on this branch. A recovery ref keeps them, but a second confirmation is needed.'],
  deleteRemoteLead: ['هذا حذف من المستودع البعيد فقط، وهو منفصل عن الحذف المحلي. يُحفظ الـcommit في مرجع استرجاع عندك.', 'This deletes on the remote only, separately from any local deletion. The commit is kept in a recovery ref on your computer.'],
  localKept: ['فرعك المحلي يبقى.', 'Your local branch stays.'],
  remoteKept: ['النسخة البعيدة، إن وُجدت، لا تُمس.', 'The remote copy, if any, is not touched.'],
  confirmDelete: ['أكّد الحذف', 'Confirm the deletion'],
  confirmUnmerged: ['نعم، احذف commits غير المدموجة (تبقى قابلة للاسترجاع)', 'Yes, delete the unmerged commits (they stay recoverable)'],
  cancel: ['إلغاء', 'Cancel'],
  done: ['تم', 'Done'],
  failed: ['ما تم', 'Not done'],
  openRun: ['افتح التشغيل {id}', 'Open run {id}'],
  readOnlySnapshot: ['هذه نسخة للقراءة فقط: تعرض ما سُجّل وقت بناء التقرير، ولا تغيّر git. افتح الاستوديو الحي لإدارة الفروع.',
    'This is a read-only snapshot: it shows what was recorded when the report was built and cannot change git. Open the live Studio to manage branches.'],
  // runs
  workBranch: ['فرع العمل', 'Work branch'],
  notCreatedYet: ['لم يُنشأ بعد', 'Not created yet'],
  noBranchRequired: ['لا يحتاج فرعًا', 'No branch required'],
  noneCreated: ['ما أُنشئ فرع', 'No branch was created'],
  branchDeleted: ['حُذف الفرع', 'The branch was deleted'],
  branchMergedDeleted: ['دُمج ثم حُذف', 'Merged, then deleted'],
  runBase: ['صُنع على {b}', 'Made on {b}'],
  actedOn: ['عمل على: {b}', 'Acted on: {b}'],
  // freshness sheet
  freshFreshLead: ['الفرع ما زال عند الـcommit الذي فُحص، بلا تعديلات غير محفوظة.', 'The branch is still at the commit that was checked, with no unsaved changes.'],
  freshFreshDetached: ['الكود المفتوح (HEAD منفصل) ما زال عند الـcommit الذي فُحص، بلا تعديلات غير محفوظة.', 'The checkout (a detached HEAD) is still at the commit that was checked, with no unsaved changes.'],
  freshEaosOnly: ['بعد الفحص جاءت فقط تعديلات EAOS المعتمدة، فالفحص ما زال صالحًا.', 'Only EAOS\'s own accepted fixes came after the scan, so it still holds.'],
  freshBehindLead: ['جاء بعد الفحص {c} commit غيّرت {f} ملف:', '{c} commit(s) came after the scan, changing {f} file(s):'],
  freshRewrittenLead: ['الـcommit الذي فُحص لم يعد في تاريخ هذا الفرع (إعادة كتابة أو reset أو force-push): التقرير قد لا يطابق الكود.', 'The scanned commit is no longer in this branch\'s history (a rewrite, reset or force-push): the report may not match the code.'],
  freshDirtyLead: ['الكود عند الـcommit الذي فُحص، لكن فيه تعديلات غير محفوظة ({n}).', 'The code is at the scanned commit, but it has unsaved changes ({n}).'],
  freshOtherLead: ['الفحص لفرع {s}، والاستوديو يحلّل الآن {b}.', 'The scan is of {s}, and the Studio now analyses {b}.'],
  freshUpdatedLead: ['EAOS تحدّث بعد هذا الفحص: أعد الفحص ليقرأ المشروع بالنسخة الجديدة.', 'EAOS was updated after this scan: re-scan to read the project with the new version.'],
  freshLegacyLead: ['تقرير قديم: فحصه لم يسجّل الفرع ولا الـcommit ولا التعديلات غير المحفوظة، فلا يمكن مقارنته بالكود. أعد الفحص بلمسة واحدة ليُسجَّل كل ذلك.',
    'An older report: its scan recorded neither the branch, the commit nor unsaved changes, so it cannot be compared with the code. Re-scan in one tap to record all of it.'],
  freshUnknownLead: ['غير معروف: {why}.', 'Unknown: {why}.'],
  whyNotScanned: ['المشروع لم يُفحص بعد', 'the project has not been scanned yet'],
  whyNotGit: ['المجلد ليس مستودع git', 'the folder is not a git repository'],
  whyBranchMissing: ['الفرع لم يعد موجودًا', 'the branch no longer exists'],
  whyOffline: ['الاستوديو الحي غير متصل الآن', 'the live Studio is not connected now'],
  scannedBranch: ['الفرع المفحوص', 'Scanned branch'],
  scannedCommit: ['الـcommit المفحوص', 'Scanned commit'],
  scannedDirty: ['تعديلات غير محفوظة وقت الفحص', 'Unsaved changes at scan time'],
  headNow: ['رأس الفرع الآن', 'Branch head now'],
  checkedAt: ['آخر تحقق', 'Last checked'],
  yes: ['نعم', 'Yes'],
  no: ['لا', 'No'],
  legacyNotRecorded: ['غير مسجّل (تقرير قديم)', 'Not recorded (older report)'],
  moreFiles: ['و{n} ملف آخر', 'and {n} more files'],
  rescanNow: ['أعد الفحص الآن', 'Re-scan now'],
  rescanBranch: ['أعد فحص هذا الفرع ({b})', 'Re-scan this branch ({b})'],
  rescanSaved: ['حُفظ الطلب، ينتظر دوره', 'Saved, waiting its turn'],
  rescanRunning: ['يفحص الآن…', 'Scanning now…'],
  rescanDone: ['انتهى الفحص، والتقرير محدّث', 'Scan done, the report is up to date'],
  rescanFailed: ['ما اكتمل الفحص', 'The scan did not finish'],
  copyFallback: ['بديل: انسخ تعليمات لمساعد', 'Fallback: copy an instruction for an assistant'],
  copyFallbackLead: ['للحالات التي لا يكون فيها الاستوديو الحي متصلًا: تعليمات كاملة يشغّلها مساعدك فيتحدّث الاستوديو.', 'For when the live Studio is not connected: a complete instruction your assistant runs to bring the Studio up to date.'],
  openLive: ['افتح الاستوديو الحي', 'Open live Studio'],
  openLiveLead: ['شغّل هذا الأمر في مجلد مشروعك على جهازك، فيفتح الاستوديو الحي الذي يعيد الفحص ويدير الفروع مباشرة:', 'Run this command in your project folder on your computer; it opens the live Studio, which re-scans and manages branches directly:'],
  copied: ['نُسخ', 'Copied'],
  // settings
  timeZone: ['المنطقة الزمنية', 'Time zone'],
  timeZoneDevice: ['منطقة الجهاز ({z})', 'This device ({z})'],
  timeZoneLead: ['كل الأوقات تُعرض بهذه المنطقة؛ المحفوظ يبقى بتوقيت UTC.', 'Every time is shown in this zone; what is stored stays in UTC.'],
  // direct control on other pages
  startStep: ['ابدأ هذه الخطوة', 'Start this step'],
  runNextStep: ['نفّذ الخطوة التالية', 'Run the next step'],
  askAboutNow: ['اسأل مساعدك عنها', 'Ask your assistant about it'],
  captureNow: ['التقط الشاشات الآن', 'Capture the screens now'],
  // switcher
  switchBranch: ['اختر فرع التحليل', 'Choose the analysis branch'],
  allBranchesLink: ['كل الفروع وإدارتها', 'All branches and their management'],
  branchChip: ['فرع التحليل: {b}', 'Analysis branch: {b}'],
} as const satisfies Record<string, readonly [string, string]>

export type BranchWord = keyof typeof BRANCH_WORDS

export function useBranchWords() {
  return useWordTable(BRANCH_WORDS)
}
