// The command centre's words (selection, preview, runs, questions), Arabic first and English equally finished.
// Kept apart from i18n/catalog.ts like the maps' words; a key missing in one language is a type error. The labels
// of actions, verbs and run states come from the contract itself (data/actions/contract.ts).
import { useWordTable } from '../map/words'

export const CMD_WORDS = {
  // selection and the action bar
  select: ['اختر', 'Select'],
  selectCard: ['اختر {id}', 'Select {id}'],
  selectStep: ['اختر بطاقات الخطوة {id}', 'Select the cards of step {id}'],
  selectedN: ['{n} مختارة', '{n} selected'],
  selectionCapped: ['الاختيار يتسع لـ {n} بطاقة كحد أقصى.', 'A selection holds at most {n} cards.'],
  clearSelection: ['ألغِ الاختيار', 'Clear the selection'],
  selectShown: ['اختر الظاهر ({n})', 'Select the shown ({n})'],
  selectGroup: ['اختر مجموعة', 'Select a group'],
  selectGroupLead: ['اختر مجموعة بطاقات مرة واحدة: حسب المجال أو الخطورة أو المكوّن أو الفجوة أو العملية أو خطوة الخطة.', 'Pick a whole group of cards at once: by area, severity, component, gap, operation or plan step.'],
  byArea: ['حسب المجال', 'By area'],
  bySeverity: ['حسب الخطورة', 'By severity'],
  byComponent: ['حسب المكوّن', 'By component'],
  byGap: ['حسب الفجوة', 'By gap'],
  byOperation: ['حسب العملية', 'By operation'],
  byStep: ['حسب خطوة الخطة', 'By plan step'],
  groupNone: ['لا توجد مجموعات من هذا النوع في هذا التقرير.', 'This report has no groups of this kind.'],
  selectItsCards: ['اختر بطاقاته ({n})', 'Select its cards ({n})'],
  actionsFor: ['أوامر للمختار', 'Actions for the selection'],
  shiftHint: ['Shift مع النقر يختار ما بينهما', 'Shift-click selects everything between'],
  // preview
  previewTitle: ['قبل التشغيل', 'Before it runs'],
  whatChanges: ['ما سيحدث', 'What will happen'],
  cardsN: ['البطاقات ({n})', 'Cards ({n})'],
  leftOutN: ['مستبعدة ({n})', 'Left out ({n})'],
  filesN: ['الملفات ({n})', 'Files ({n})'],
  batchesN: ['الدفعات ({n})', 'Batches ({n})'],
  batchCards: ['الدفعة {n} · {c} بطاقة', 'Batch {n} · {c} cards'],
  time: ['الوقت', 'Time'],
  minutes: ['{a}–{b} دقيقة', '{a}–{b} min'],
  minutesUnknown: ['لا يوجد أساس للتقدير بعد', 'No basis for an estimate yet'],
  risk: ['الخطر', 'Risk'],
  riskLow: ['قليل', 'Low'],
  riskMedium: ['متوسط', 'Medium'],
  riskHigh: ['عالٍ', 'High'],
  onFailure: ['لو فشل', 'If it fails'],
  assistant: ['المساعد', 'Assistant'],
  notInstalled: ['غير مثبّت', 'not installed'],
  notLoggedIn: ['غير مسجّل الدخول', 'not logged in'],
  ready: ['جاهز', 'ready'],
  handoffLead: ['لا يوجد مساعد جاهز على هذا الجهاز. الطلب ينتظر أول مساعد يسأل EAOS عن الحال، أو انسخه وألصقه له.', 'No assistant is ready on this computer. The request waits for the next assistant that asks EAOS where things stand, or copy it and paste it to yours.'],
  copyRequest: ['انسخ الطلب', 'Copy the request'],
  irreversibleLead: ['هذا لا رجعة فيه من هنا.', 'This cannot be undone from here.'],
  understand: ['فهمت، وأريد المتابعة', 'I understand, and I want to go on'],
  consentLead: ['يحتاج موافقتك مرة واحدة لتشغيل تطبيقك في النسخة المعزولة؛ سيسألك في صندوق القرارات.', 'It needs your one-time consent to run your app in the isolated copy; it asks you in the Decisions inbox.'],
  cancel: ['إلغاء', 'Cancel'],
  startVerb: ['ابدأ: {verb} ({n})', 'Start: {verb} ({n})'],
  startAction: ['شغّل: {label}', 'Run: {label}'],
  previewIt: ['اعرض ما سيحدث', 'Show what will happen'],
  loadingPreview: ['أجهّز المعاينة…', 'Preparing the preview…'],
  previewFailed: ['ما قدرت أجهّز المعاينة', 'The preview could not be prepared'],
  startFailed: ['ما بدأ التشغيل', 'The run did not start'],
  started: ['بدأ: {label}', 'Started: {label}'],
  queuedToast: ['في الطابور: {label}', 'Queued: {label}'],
  inputs: ['المدخلات', 'Inputs'],
  required: ['مطلوب', 'required'],
  // snapshot mode
  snapshotTitle: ['الأوامر تشتغل من الاستوديو الحي', 'Actions run from the live Studio'],
  snapshotStep1: ['افتح الطرفية في مجلد المشروع', 'Open a terminal in the project folder'],
  snapshotStep2: ['اكتب هذا الأمر، فيفتح الاستوديو الحي في متصفحك:', 'Type this command; the live Studio opens in your browser:'],
  copyCommand: ['انسخ الأمر', 'Copy the command'],
  orAssistant: ['أو اطلبه من مساعدك مباشرة:', 'Or ask your assistant directly:'],
  watchExample: ['شاهد تشغيلًا تجريبيًا', 'Watch an example run'],
  demoBanner: ['تشغيل تجريبي مسجّل: لا شيء يتغير في مشروعك.', 'An example, replayed from a recording: nothing changes in your project.'],
  leaveDemo: ['اخرج من التجربة', 'Leave the example'],
  // runs
  runs: ['التشغيل', 'Runs'],
  runsLead: ['كل ما طلبته من EAOS: ما يشتغل الآن، وما ينتظر دوره، وما انتهى.', 'Everything you asked EAOS to do: what runs now, what waits its turn, and what is done.'],
  now: ['الآن', 'Now'],
  nothingRunning: ['لا شيء يشتغل الآن.', 'Nothing is running now.'],
  nothingRunningSub: ['اختر بطاقات في المشاكل أو خطوة في الخطة، ثم اختر أمرًا. أو افتح البحث (⌘K) واكتب اسم الأمر.', 'Select cards on Problems or a step of the plan, then pick a verb. Or open search (⌘K) and type the action’s name.'],
  queue: ['الطابور', 'Queue'],
  queueLead: ['يشتغل واحد في كل مرة، بهذا الترتيب.', 'One runs at a time, in this order.'],
  queueEmpty: ['لا شيء ينتظر.', 'Nothing is waiting.'],
  moveUp: ['قدّم {label}', 'Move {label} up'],
  moveDown: ['أخّر {label}', 'Move {label} down'],
  removeFromQueue: ['أخرج {label} من الطابور', 'Take {label} out of the queue'],
  history: ['السجل', 'History'],
  searchRuns: ['ابحث في التشغيل', 'Search the runs'],
  all: ['الكل', 'All'],
  finished: ['انتهى', 'Done'],
  notFinished: ['ما اكتمل', 'Not finished'],
  noRuns: ['لا يوجد تشغيل بعد.', 'No run yet.'],
  noRunsMatch: ['لا تشغيل يطابق البحث.', 'No run matches.'],
  cardsCount: ['{n} بطاقة', '{n} cards'],
  took: ['استغرق {d}', 'took {d}'],
  attempt: ['المحاولة {n}', 'attempt {n}'],
  outcomeAccepted: ['اعتُمد', 'Accepted'],
  outcomeUndone: ['رُمي', 'Undone'],
  waitsForYou: ['ينتظر قرارك', 'Waits for your decision'],
  positionN: ['رقم {n} في الطابور', 'Number {n} in the queue'],
  // the run page
  run: ['التشغيل', 'Run'],
  runNotFound: ['هذا التشغيل غير موجود', 'This run is not here'],
  runNotFoundSub: ['ربما بدأ من استوديو آخر أو حُذف سجله. ارجع إلى قائمة التشغيل.', 'It may have started from another Studio, or its log was removed. Go back to the runs.'],
  pause: ['إيقاف مؤقت', 'Pause'],
  resume: ['استئناف', 'Resume'],
  stop: ['إيقاف', 'Stop'],
  retry: ['أعد المحاولة', 'Retry'],
  stopConfirm: ['أوقف هذا التشغيل؟ ما انتهى منه يبقى في سجله، ولا يصل شيء لفرعك.', 'Stop this run? What it did stays in its log, and nothing reaches your branch.'],
  stopYes: ['نعم، أوقفه', 'Yes, stop it'],
  progress: ['التقدم', 'Progress'],
  batchN: ['الدفعة {n}', 'Batch {n}'],
  doneOfTotal: ['{d} من {t}', '{d} of {t}'],
  overall: ['الإجمالي', 'Overall'],
  waitingTurn: ['ينتظر دوره: رقم {n} في الطابور.', 'Waiting its turn: number {n} in the queue.'],
  noProgressYet: ['يظهر التقدم مع أول دفعة.', 'Progress shows with the first batch.'],
  whatHappened: ['ما حدث خطوة بخطوة', 'What happened, step by step'],
  readN: ['قرأ {n} ملفات', 'Read {n} files'],
  showChange: ['اعرض التغيير', 'Show the change'],
  hideChange: ['أخفِ التغيير', 'Hide the change'],
  showDetail: ['التفاصيل التقنية', 'Technical detail'],
  hideDetail: ['أخفِ التفاصيل', 'Hide the detail'],
  kept: ['قُبل', 'kept'],
  leftOut: ['تُرك', 'left out'],
  passed: ['نجح', 'passed'],
  failed: ['فشل', 'failed'],
  screens: ['الشاشات قبل وبعد', 'Screens before and after'],
  before: ['قبل', 'Before'],
  after: ['بعد', 'After'],
  screenSaved: ['اللقطة محفوظة في {path}', 'Screenshot saved at {path}'],
  connecting: ['أتصل…', 'Connecting…'],
  reconnecting: ['انقطع الاتصال، أعيد الاتصال وأكمل من حيث توقفت…', 'Connection lost; reconnecting and picking up where it stopped…'],
  elapsed: ['مضى {d}', '{d} so far'],
  latestStep: ['الخطوة الحالية', 'Current step'],
  // result
  result: ['النتيجة', 'Result'],
  branch: ['الفرع', 'Branch'],
  changes: ['التغييرات', 'Changes'],
  filesCount: ['{n} ملفات', '{n} files'],
  tests: ['الفحوص', 'Checks'],
  cardsClosed: ['البطاقات المغلقة ({n})', 'Cards closed ({n})'],
  indicators: ['المؤشرات', 'Indicators'],
  acceptBranch: ['اعتمد الفرع', 'Accept the branch'],
  undoBranch: ['ارمِ الفرع', 'Undo the branch'],
  acceptTitle: ['اعتماد {branch}', 'Accept {branch}'],
  undoTitle: ['رمي {branch}', 'Undo {branch}'],
  acceptLead: ['يدمج EAOS هذا الفرع في فرعك. لا رجعة فيه من هنا.', 'EAOS merges this branch into yours. This cannot be undone from here.'],
  undoLead: ['يرمي EAOS هذا الفرع وكل ما فيه. لا رجعة فيه من هنا.', 'EAOS throws this branch away with everything on it. This cannot be undone from here.'],
  acceptYes: ['نعم، اعتمده', 'Yes, accept it'],
  undoYes: ['نعم، ارمِه', 'Yes, throw it away'],
  decided: ['تم: {what}', 'Done: {what}'],
  decideFailed: ['ما تم القرار', 'The decision did not go through'],
  answer: ['الجواب', 'Answer'],
  errorTitle: ['ما اكتمل التشغيل', 'The run did not finish'],
  // questions
  runAsks: ['التشغيل يسألك', 'A run asks you'],
  fromRun: ['من: {label}', 'From: {label}'],
  recommended: ['الموصى به', 'Recommended'],
  answerWith: ['أجب: {label}', 'Answer: {label}'],
  otherAnswers: ['أجوبة أخرى', 'Other answers'],
  writeAnswer: ['اكتب جوابًا آخر', 'Write another answer'],
  send: ['أرسل', 'Send'],
  answered: ['وصل جوابك، والتشغيل يكمل.', 'Your answer is in; the run goes on.'],
  answerFailed: ['ما وصل الجواب', 'The answer did not go through'],
  dismiss: ['لاحقًا', 'Later'],
  questionsFromRuns: ['أسئلة من التشغيل', 'Questions from runs'],
  openRun: ['افتح التشغيل', 'Open the run'],
  runningPill: ['{state}: {label}', '{state}: {label}'],
  // palette
  kindAction: ['أمر', 'Action'],
  verbOnSelection: ['{verb} المختار ({n})', '{verb} the selection ({n})'],
} satisfies Record<string, readonly [string, string]>

export type CmdWord = keyof typeof CMD_WORDS

export function useCmdWords() {
  return useWordTable(CMD_WORDS)
}
