import http from 'k6/http';
import { check } from 'k6';

// Generated by EAOS from intake.json $scenario ($source): $stimulus.
// BASE_URL comes from the environment; nothing here names a host.
export const options = {
  scenarios: {
    load: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: '1m', target: $users },
        { duration: '3m', target: $users },
        { duration: '1m', target: 0 },
      ],
    },
  },
  thresholds: {
    http_req_duration: ['p(95)<$p95'],
    http_req_failed: ['rate<$error_rate'],
  },
};

const BASE_URL = __ENV.BASE_URL;
const PATHS = $paths;

export default function () {
  for (const path of PATHS) {
    const response = http.get(`$${BASE_URL}$${path}`);
    check(response, { 'answers without a server error': (r) => r.status < 500 });
  }
}
