"""The behaviour lock: a spec for every feature, describing what the system does today, before anything changes.

Generation is static: nothing from the project runs here. Each feature (features.json) gets specs in its
own tool's format, written under behavior-lock/ in the report:

  pages          Playwright (behavior-lock/playwright/<feature>.spec.ts): every route is opened, its console
                 errors and page errors are compared with a text snapshot, and the page with a screenshot.
                 The first run on the original code (NS26) records both; that recording is the lock.
  http routes    Playwright request tests: a GET's status is recorded the same way. A route that writes is
                 not called blindly: it is skipped and marked needs_fixture.
  Python code    ApprovalTests (behavior-lock/approvals/test_<feature>.py): the public interface of the
                 feature's import-safe modules (names and signatures) is approved as it is today. A module
                 whose top level runs code (a Streamlit page, a script) is never imported.

A route with a parameter ($id, :id) reads it from E2E_<PARAM>; without it the test is skipped and the
surface is marked needs_fixture in plan.json, never dropped. Sign-in, when the owner grants E2E_USER and
E2E_PASSWORD (authorization.json -> env_allow), happens once in auth.setup.ts; no value is written here.
Every spec describes today's behaviour, not the intended one: a console error today is recorded, not fixed.

run_lock() is the screens part of the flow `safety` of the live map (FLOW, written by eaos/guided.py:safety_run to
<runtime>/progress/safety.jsonl): each pass runs with EAOS's stream reporter (eaos/templates/screens/
stream-reporter.mjs), which writes a line per test to behavior-lock/stream.jsonl as it begins and ends; Screens
follows that file and reports one step per spec file, with its shot once written.
"""
import ast
import contextvars
import json
import re
import shutil
import threading
from pathlib import Path

from . import progress
from .progress.flow import OPTIONAL, Stage

PAGE, HTTP = 'page', 'http'
PARAM = re.compile(r'\$(\w+)|:(\w+)')
SAFE = (ast.Import, ast.ImportFrom, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Assign, ast.AnnAssign)
REQUIREMENTS = 'approvaltests==19.1.1\npytest==9.1.1\n'

CONFIG = """import path from 'node:path';
import { defineConfig, devices } from '@playwright/test';

// Generated by EAOS. BASE_URL points at the running application; nothing here names a host.
export default defineConfig({
  testDir: './playwright',
  snapshotPathTemplate: '{testDir}/../__screenshots__/{testFilePath}/{arg}{ext}',
  // The raw Playwright report; NS26 turns a run into behavior-lock/results.json, the contract artifact.
  reporter: [['json', { outputFile: 'playwright-report.json' }]],
  use: { baseURL: process.env.BASE_URL, storageState: path.join(__dirname, '.auth', 'user.json') },
  projects: [
    { name: 'setup', testMatch: /auth\\.setup\\.ts/ },
    { name: 'lock', dependencies: ['setup'], use: { ...devices['Desktop Chrome'] } },
  ],
});
"""

AUTH = """import fs from 'node:fs';
import path from 'node:path';
import { test as setup } from '@playwright/test';

// Generated by EAOS. Signs in once when the owner granted E2E_USER and E2E_PASSWORD; otherwise the lock
// runs signed out. E2E_LOGIN_PATH overrides the sign-in page when it is not /login.
const file = path.join(__dirname, '..', '.auth', 'user.json');

setup('sign in once, if credentials were granted', async ({ page }) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const user = process.env.E2E_USER;
  const password = process.env.E2E_PASSWORD;
  if (!user || !password) {
    fs.writeFileSync(file, JSON.stringify({ cookies: [], origins: [] }));
    setup.skip(true, 'no E2E_USER and E2E_PASSWORD: the lock runs signed out');
    return;
  }
  await page.goto(process.env.E2E_LOGIN_PATH ?? '/login');
  await page.locator('input[type="email"], input[name="email"], input[name="username"]').first().fill(user);
  await page.locator('input[type="password"]').first().fill(password);
  await page.locator('button[type="submit"], input[type="submit"]').first().click();
  await page.waitForLoadState('networkidle');
  await page.context().storageState({ path: file });
});
"""


def slug(text):
    return re.sub(r'[^a-z0-9]+', '-', str(text).lower()).strip('-') or 'root'


def surfaces(out):
    """{route: (surface kind, http method, file)} from the entry-point facts."""
    try: facts = json.loads((Path(out) / 'facts/entrypoints.json').read_text(encoding='utf-8'))['facts']
    except (OSError, ValueError, KeyError): return {}
    found = {}
    for fact in facts:
        value = fact.get('value') or {}
        if fact.get('kind') == 'entry_point' and value.get('route'):
            row = (value.get('surface'), (value.get('http_method') or 'GET').upper(), (fact.get('location') or {}).get('path'))
            found.setdefault(value['route'], row)
            # A command's feature names it by its file (run_app.py), not by its route (run_app).
            if value.get('surface') == 'cli' and row[2]: found.setdefault(row[2], row)
    return found


def kind_of(surface, known):
    """page, http or cli: from the entry-point facts; a surface they do not know is a page only if it is a URL."""
    if surface in known: return known[surface]
    return (PAGE if surface.startswith('/') or surface == '*' else 'cli', 'GET', None)


def path_of(route):
    """The URL a route id is served at, or None for a layout that has no URL of its own.

    TanStack Router ids name files, not URLs: a segment starting with `_` is a pathless layout and is not in
    the URL; a trailing `_` only un-nests the route (`cartoes_/faturas` is served at `/cartoes/faturas`);
    `(group)` segments (Next.js) are not in the URL either."""
    if route == '__root__': return None
    parts = [part for part in route.split('/') if part]
    if parts and parts[-1].startswith('_') and not parts[-1].startswith('__'): return None
    kept = [part.rstrip('_') if part.endswith('_') and not part.startswith('$') else part
            for part in parts if not (part.startswith('_') or (part.startswith('(') and part.endswith(')')))]
    return '/' + '/'.join(kept)


def url(route):
    """A route as a TypeScript template literal, parameters read from E2E_<PARAM>; and the parameters."""
    if route == '*': return '`/__eaos_unknown_route__`', []
    route = path_of(route) or route
    params = [a or b for a, b in PARAM.findall(route)]
    literal = PARAM.sub(lambda m: '${process.env.E2E_' + (m.group(1) or m.group(2)).upper() + " ?? ''}", route)
    return '`' + literal.replace('`', '\\`') + '`', params


def playwright_spec(feature, rows):
    """The spec text for a feature's pages and http routes, and the plan's surface list."""
    lines = ["import { test, expect } from '@playwright/test';", '',
             f"// Generated by EAOS from features.json: what \"{feature['name']}\" does today. The first run on the",
             '// original code records the snapshots; every later run must match them.', '',
             f"test.describe({json.dumps(feature['name'])}, () => {{"]
    listed = []
    for route, (kind, method, _) in rows:
        if route != '*' and path_of(route) is None:
            listed.append(f'{route} (layout: no URL of its own)')
            continue
        target, params = url(route)
        # Named by the URL, not the route id: moving a file between layouts must not orphan its recording.
        name = slug(path_of(route) or route) if route != '*' else 'unknown-route'
        guard = ''.join(f"  test.skip(!process.env.E2E_{p.upper()}, 'needs_fixture: set E2E_{p.upper()}');\n" for p in params)
        marker = ' (needs_fixture)' if params else ''
        if kind == HTTP and method != 'GET':
            listed.append(f'{method} {route} (needs_fixture: writes)')
            lines += [f"  test({json.dumps(f'{method} {route} is not called blindly')}, async () => {{",
                      f"    test.skip(true, 'needs_fixture: {method} writes; lock it against a fixture');", '  });']
            continue
        listed.append(('GET ' if kind == HTTP else '') + route + marker)
        if kind == HTTP:
            lines += [f"  test({json.dumps(f'GET {route} answers as it does today')}, async ({{ request }}) => {{",
                      *(f'  {g}' for g in guard.splitlines()),
                      f"    const response = await request.get({target});",
                      f"    expect(String(response.status())).toMatchSnapshot('{name}.status.txt');", '  });']
        else:
            lines += [f"  test({json.dumps(f'{route} renders as it does today')}, async ({{ page }}) => {{",
                      *(f'  {g}' for g in guard.splitlines()),
                      '    const messages: string[] = [];',
                      "    page.on('pageerror', (error) => messages.push(`pageerror: ${error.message}`));",
                      "    page.on('console', (message) => { if (message.type() === 'error') messages.push(`console: ${message.text()}`); });",
                      f'    await page.goto({target});',
                      "    await page.waitForLoadState('networkidle');",
                      f"    expect(messages.join('\\n')).toMatchSnapshot('{name}.console.txt');",
                      f"    await expect(page).toHaveScreenshot('{name}.png', {{ fullPage: true, maxDiffPixelRatio: 0.01 }});",
                      '  });']
    lines += ['});', '']
    return '\n'.join(lines), listed


def import_safe(path):
    """Whether importing the file only defines things: no top-level statement that runs code."""
    try: tree = ast.parse(Path(path).read_text(encoding='utf-8', errors='replace'))
    except (OSError, SyntaxError): return False
    for node in tree.body:
        if isinstance(node, SAFE): continue
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant): continue   # a docstring
        if isinstance(node, ast.If) and 'name' in ast.dump(node.test) and '__main__' in ast.dump(node.test): continue
        if isinstance(node, ast.Try) and all(isinstance(n, (ast.Import, ast.ImportFrom)) for n in node.body): continue
        return False
    return True


def approval_test(feature, target):
    modules = sorted({f[:-3].replace('/', '.') for f in feature.get('files') or []
                      if f.endswith('.py') and not f.split('/')[-1].startswith('test_') and import_safe(Path(target) / f)
                      and not f.endswith('__init__.py')})
    if not modules: return None, []
    text = '\n'.join([
        f'"""Generated by EAOS: the public interface of "{feature["name"]}" as it is today, approved on the original code."""',
        'import importlib', 'import inspect', '', 'from approvaltests import verify', '',
        f'MODULES = {json.dumps(modules, indent=4)}', '', '',
        'def public_interface():',
        '    lines = []',
        '    for name in MODULES:',
        '        module = importlib.import_module(name)',
        '        for attribute in sorted(n for n in vars(module) if not n.startswith("_")):',
        '            value = getattr(module, attribute)',
        '            if (inspect.isfunction(value) or inspect.isclass(value)) and getattr(value, "__module__", None) == name:',
        '                try: signature = str(inspect.signature(value))',
        '                except (TypeError, ValueError): signature = "(...)"',
        '                lines.append(f"{name}.{attribute}{signature}")',
        '    return "\\n".join(lines)', '', '',
        'def test_the_public_interface_is_as_it_was():',
        '    verify(public_interface())', ''])
    return text, modules


def build(out, target):
    """Write behavior-lock/ and return its plan (behavior-lock/plan.json, schemas/artifacts/behavior-lock-plan)."""
    out, target = Path(out), Path(target)
    try: features = json.loads((out / 'features.json').read_text(encoding='utf-8'))['features']
    except (OSError, ValueError, KeyError): features = []
    known = surfaces(out)
    root = out / 'behavior-lock'
    specs, wrote_playwright, wrote_python = [], False, False
    for feature in features:
        rows = [(route, kind_of(route, known)) for route in feature.get('surfaces') or []]
        web = [(route, info) for route, info in rows if info[0] in (PAGE, HTTP)]
        if web:
            text, listed = playwright_spec(feature, web)
            path = f'playwright/{slug(feature["name"])}.spec.ts'
            (root / path).parent.mkdir(parents=True, exist_ok=True)
            (root / path).write_text(text, encoding='utf-8')
            specs.append({'feature': feature['name'], 'tool': 'playwright', 'path': path, 'surfaces': listed})
            wrote_playwright = True
            continue
        text, modules = approval_test(feature, target)
        if text:
            path = f'approvals/test_{slug(feature["name"]).replace("-", "_")}.py'
            (root / path).parent.mkdir(parents=True, exist_ok=True)
            (root / path).write_text(text, encoding='utf-8')
            specs.append({'feature': feature['name'], 'tool': 'approvaltests', 'path': path, 'surfaces': modules})
            wrote_python = True
        else:
            specs.append({'feature': feature['name'], 'tool': 'approvaltests', 'path': '',
                          'surfaces': [f'{s} (needs_fixture: no web surface and no import-safe module)' for s in feature.get('surfaces') or []]})
    if wrote_playwright:
        (root / 'playwright.config.ts').write_text(CONFIG, encoding='utf-8')
        (root / 'playwright/auth.setup.ts').write_text(AUTH, encoding='utf-8')
    if wrote_python:
        (root / 'approvals/requirements.txt').write_text(REQUIREMENTS, encoding='utf-8')
    plan = {'schema_version': 1, 'specs': specs}
    if specs:
        root.mkdir(parents=True, exist_ok=True)
        (root / 'plan.json').write_text(json.dumps(plan, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
    return plan


# ── NS26: the lock, run on the original code ────────────────────────────────────────────────────────────
# The browser reaches loopback only: Chromium sends every other host to a proxy nobody answers on, so a
# page's call to production or a third party fails inside the run instead of leaving the machine.
LOCK_CONFIG = """import base from './playwright.config';

// Written by EAOS for a run in the sandbox: the generated config, with every non-loopback host refused.
// Loopback is named in the bypass list: every other host goes to a proxy nobody answers on.
const offline = { launchOptions: { args: ['--proxy-server=http://127.0.0.1:9', '--proxy-bypass-list=127.0.0.1;localhost;[::1]'] } };
export default {
  ...base,
  reporter: [['json', { outputFile: process.env.EAOS_LOCK_REPORT }], ['./stream-reporter.mjs', { outputFile: process.env.EAOS_LOCK_STREAM }]],
  use: { ...base.use, ...offline },
  projects: (base.projects ?? []).map((project) => ({ ...project, use: { ...project.use, ...offline } })),
};
"""


def spec_statuses(report):
    """{spec path: (status, reason)} from a Playwright JSON report: a spec passes when none of its tests failed
    and at least one ran; one whose every test was skipped is quarantined with the skip's reason."""
    found = {}

    def walk(suite, file=None):
        file = suite.get('file') or file
        for spec in suite.get('specs') or []:
            outcomes = [(result.get('status'), (result.get('error') or {}).get('message', ''))
                        for test in spec.get('tests') or [] for result in test.get('results') or []] or \
                       [('skipped', (test.get('annotations') or [{}])[0].get('description', '')) for test in spec.get('tests') or []]
            found.setdefault(file, []).extend(outcomes)
        for child in suite.get('suites') or []: walk(child, file)
    for suite in report.get('suites') or []: walk(suite)
    statuses = {}
    for file, outcomes in found.items():
        failed = [message for status, message in outcomes if status in ('failed', 'timedOut', 'interrupted')]
        ran = [status for status, _ in outcomes if status == 'passed']
        if failed: statuses[file] = ('failed', failed[0][:300])
        elif ran: statuses[file] = ('passed', '')
        else: statuses[file] = ('quarantined', 'every test was skipped: ' + (next((m for s, m in outcomes if m), '') or 'needs a fixture'))
    return statuses


def _prepare(live, report, snapshots=None):
    """The lock folder in the sandbox copy: the report's specs, the offline config, and recorded snapshots if given."""
    lock = live.sandbox.copy / '.eaos-lock'
    shutil.rmtree(lock, ignore_errors=True)
    shutil.copytree(Path(report) / 'behavior-lock', lock)
    (lock / 'lock.config.ts').write_text(LOCK_CONFIG, encoding='utf-8')
    shutil.copyfile(REPORTER, lock / REPORTER.name)
    # The specs import @playwright/test, which most projects do not install; ES modules ignore NODE_PATH. The
    # lock always runs EAOS's pinned Playwright, the version its installed browsers belong to.
    from .toolchain import home
    modules = home() / 'node/node_modules'
    if modules.is_dir() and not (lock / 'node_modules').exists(): (lock / 'node_modules').symlink_to(modules, target_is_directory=True)
    # Its own package.json: a project declaring "type": "module" must not change how the lock's files load.
    (lock / 'package.json').write_text('{"private": true, "type": "commonjs"}\n', encoding='utf-8')
    (lock / '.auth').mkdir(exist_ok=True)
    (lock / '.auth/user.json').write_text(json.dumps({'cookies': [], 'origins': []}), encoding='utf-8')
    if snapshots is not None:
        shutil.rmtree(lock / '__screenshots__', ignore_errors=True)
        shutil.copytree(snapshots, lock / '__screenshots__')
    return lock


def _start(live, lock):
    """Set up, start and seed the project; the address it answers on."""
    live.setup()
    base = live.start()
    # A seed may sign the browser in or choose its workspace: it writes Playwright's storage state to
    # EAOS_STORAGE_STATE, and the lock opens every screen with it; the fixtures it prints join the environment.
    live.seed(base, lock / '.auth/user.json')
    return base


def _pass(live, lock, base, output, update):
    output.parent.mkdir(parents=True, exist_ok=True)
    argv = ['playwright', 'test', '--config', 'lock.config.ts', '--project=lock', '--no-deps', '--workers=1',
            *(['--update-snapshots=all'] if update else [])]
    stream = output.parent / STREAM
    if stream.exists(): stream.unlink()
    screens = Screens(stream, lock / '__screenshots__', output.parent / 'snapshots', keep=update).start()
    try:
        code, out, err = live.sandbox.run(argv, timeout=3600, network=True, cwd='.eaos-lock',
                                          env={**live.extra(), 'BASE_URL': base, 'EAOS_LOCK_REPORT': str(output),
                                               'EAOS_LOCK_STREAM': str(stream)})
    finally:
        screens.stop()
    live.log.append({'argv': argv, 'exit': code, 'tail': (out + err)[-3000:]})     # why a spec did not run
    try: return json.loads(output.read_text(encoding='utf-8'))
    except (OSError, ValueError): return {}


def _results(report, statuses):
    results = []
    for spec in json.loads((Path(report) / 'behavior-lock/plan.json').read_text(encoding='utf-8'))['specs']:
        name = Path(spec['path']).name
        status, reason = next(((s, r) for file, (s, r) in statuses.items() if Path(file).name == name),
                              ('error', 'the spec did not run'))
        results.append({'path': spec['path'], 'status': status, **({'reason': reason} if reason else {})})
    return results


def _write(runtime, name, live, results):
    record = {'schema_version': 1, 'commit': live.commit, 'backend': 'unshare' if live.sandbox.offline else 'process',
              'results': results, 'limitations': sorted(set(live.sandbox.limitations))}
    (Path(runtime) / 'behavior-lock').mkdir(parents=True, exist_ok=True)
    (Path(runtime) / 'behavior-lock' / name).write_text(json.dumps(record, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
    return record


# ── the live map: the safety flow, and each screen as it is recorded ───────────────────────────────────────
REPORTER = Path(__file__).resolve().parent / 'templates/screens/stream-reporter.mjs'
STREAM = 'stream.jsonl'
FLOW = (
    Stage('prepare', description='Copy the report\'s screen specs into the separate copy, with the offline browser settings'),
    Stage('start', requires=('prepare',), description='Install, start and sign in to the app in the separate copy'),
    Stage('record', requires=('start',), description='Open every screen once and record how it looks today'),
    Stage('verify', requires=('record',),
          description='Open every screen again and compare it with the recording: a screen that differs between two '
                      'runs of the same code is not steady and cannot guard a change'),
    Stage('speed', requires=('start',), necessity=OPTIONAL,
          absent_when='the app has no production build, or its production run did not work during the setup',
          description='Measure how fast the production build answers under many users (k6)'),
)
FAILED_STATUSES = ('failed', 'timedOut', 'interrupted')


class Screens:
    """Follows the stream reporter's lines while one pass runs, and reports one step per spec file of the running
    stage (eaos/progress): running at its first test, then ok, failed or skipped once all its tests ended, with the
    seconds they took and the spec's first shot. With `keep`, the shot is copied at once to where the recording is
    kept (`snapshots`), the same file run_lock copies there after the pass. Never raises; a no-op outside a flow."""

    def __init__(self, stream, shots, snapshots, keep=False, every=0.5):
        self.stream, self.shots, self.snapshots, self.keep, self.every = Path(stream), Path(shots), Path(snapshots), keep, every
        self.offset, self.buffer = 0, b''
        self.planned, self.outcomes, self.seconds, self.finished = {}, {}, {}, []
        self.halt = threading.Event()
        self.thread = None

    def start(self):
        if progress.current() is None: return self
        self.thread = threading.Thread(target=contextvars.copy_context().run, args=(self._follow,), daemon=True,
                                       name='eaos-screens')
        self.thread.start()
        return self

    def stop(self):
        self.halt.set()
        if self.thread is not None:
            self.thread.join(timeout=5)
            self.thread = None
            try: self.read()
            except Exception: pass
        return self

    def _follow(self):
        while not self.halt.wait(self.every):
            try: self.read()
            except Exception: pass

    def read(self):
        """The lines written since the last read, each reported; a line still being written waits for its end."""
        try:
            with self.stream.open('rb') as handle:
                handle.seek(self.offset)
                chunk = handle.read()
        except OSError:
            return
        self.offset += len(chunk)
        self.buffer += chunk
        *lines, self.buffer = self.buffer.split(b'\n')
        for line in lines:
            try: row = json.loads(line)
            except ValueError: continue
            if isinstance(row, dict): self.handle(row)

    def handle(self, row):
        event, name = row.get('event'), row.get('file')
        total = len(self.planned)
        if event == 'plan':
            self.planned = {str(f): int(n) for f, n in (row.get('files') or {}).items()}
            total = len(self.planned)
            for name in self.planned: progress.step(name, 0, total, 'waiting')
        elif event == 'test.begin' and name in self.planned and name not in self.outcomes:
            self.outcomes[name] = []
            progress.step(name, len(self.finished), total, 'running')
        elif event == 'test.end' and name in self.planned and name not in self.finished:
            self.outcomes.setdefault(name, []).append((row.get('status'), row.get('error') or ''))
            self.seconds[name] = self.seconds.get(name, 0.0) + (row.get('duration') or 0) / 1000
            if len(self.outcomes[name]) < self.planned[name]: return
            self.finished.append(name)
            status, reason, code = self.verdict(self.outcomes[name])
            progress.step(name, len(self.finished), total, status, round(self.seconds[name], 2), reason, code,
                          artifact=self.shot(row.get('shots') or []))

    @staticmethod
    def verdict(outcomes):
        """(status, reason, reason_code) of one spec file, by the rule of spec_statuses()."""
        failed = [error for status, error in outcomes if status in FAILED_STATUSES]
        if failed: return 'failed', failed[0][:200], 'screen_failed'
        if any(status == 'passed' for status, _ in outcomes): return 'ok', '', ''
        return 'skipped', 'every test was skipped: it needs a fixture', 'screen_needs_fixture'

    def shot(self, shots):
        """The spec's first shot, as a path relative to the run's folder (behavior-lock/snapshots/...), or ''."""
        for name in shots:
            source = self.shots / name
            if '..' in Path(name).parts or not source.is_file(): continue
            kept = self.snapshots / name
            if self.keep:
                try:
                    kept.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copyfile(source, kept)
                except OSError:
                    continue
            return f'{self.snapshots.parent.name}/{self.snapshots.name}/{name}'
        return ''


def run_lock(report, target, runtime):
    """behavior-lock/results.json in `runtime`: the report's specs, run twice on the original code in the sandbox.

    The first pass records each screen as it is today (the snapshots, kept in behavior-lock/snapshots for every
    later run); the second must match it. A spec that passes the second pass locks today's behaviour; one that
    differs between two runs of the same code is not deterministic and fails. Needs <runtime>/authorization.json
    granting S05 and <runtime>/run.json."""
    from .live_run import LiveRun
    report, runtime = Path(report), Path(runtime)
    progress.begin('prepare')
    live = LiveRun(target, runtime, 'S05')
    lock = _prepare(live, report)
    try:
        progress.begin('start')
        base = _start(live, lock)
        progress.begin('record')
        _pass(live, lock, base, runtime / 'behavior-lock/playwright-record.json', update=True)
        snapshots = runtime / 'behavior-lock/snapshots'
        shutil.rmtree(snapshots, ignore_errors=True)
        if (lock / '__screenshots__').is_dir(): shutil.copytree(lock / '__screenshots__', snapshots)
        progress.begin('verify')
        verify = _pass(live, lock, base, runtime / 'behavior-lock/playwright-verify.json', update=False)
        results = _results(report, spec_statuses(verify))
        progress.end('verify', detail={'screens': len(results), 'passed': sum(r['status'] == 'passed' for r in results)})
    finally:
        live.stop()
        live.record('behavior-lock/run-log.json')
    return _write(runtime, 'results.json', live, results)


def verify_lock(report, target, runtime, name='results-after'):
    """The lock recorded on the original, run once on `target` (a candidate EAOS committed on the granted commit):
    behavior-lock/<name>.json, and {specs, passed, failed}. No snapshot is ever updated here."""
    from .live_run import LiveRun
    report, runtime = Path(report), Path(runtime)
    snapshots = runtime / 'behavior-lock/snapshots'
    if not snapshots.is_dir(): raise RuntimeError('no snapshots recorded on the original: run `eaos live lock` first')
    live = LiveRun(target, runtime, 'S09')
    lock = _prepare(live, report, snapshots)
    try:
        base = _start(live, lock)
        verify = _pass(live, lock, base, runtime / f'behavior-lock/playwright-{name}.json', update=False)
        results = _results(report, spec_statuses(verify))
    finally:
        live.stop()
        live.record(f'behavior-lock/run-log-{name}.json')
    _write(runtime, f'{name}.json', live, results)
    # A screen that did not pass on the original (its recording failed, or it never had a snapshot) cannot be broken
    # by a change: only a screen that passed there and fails here counts against the change.
    original = runtime / 'behavior-lock/results.json'
    passed_before = ({r['path'] for r in json.loads(original.read_text(encoding='utf-8'))['results'] if r['status'] == 'passed'}
                     if original.is_file() else {r['path'] for r in results})
    failing = [r for r in results if r['status'] in ('failed', 'error')]
    return {'specs': len(results), 'passed': sum(r['status'] == 'passed' for r in results),
            'failed': sum(r['path'] in passed_before for r in failing),
            'already_failing': sorted(r['path'] for r in failing if r['path'] not in passed_before)}
