"""The behaviour lock: a spec for every feature, describing what the system does today, before anything changes.

Generation is static: nothing from the project runs here. Each feature (features.json) gets specs in its
own tool's format, written under behavior-lock/ in the report:

  pages          Playwright (behavior-lock/playwright/<feature>.spec.ts): every route is opened, its console
                 errors and page errors are compared with a text snapshot, and the page with a screenshot.
                 The first run on the original code (NS26) records both; that recording is the lock.
  http routes    Playwright request tests: a GET's status is recorded the same way. A route that writes is
                 not called blindly: it is skipped and marked needs_fixture.
  Python code    ApprovalTests (behavior-lock/approvals/test_<feature>.py): the public interface of the
                 feature's import-safe modules (names and signatures) is approved as it is today. A module
                 whose top level runs code (a Streamlit page, a script) is never imported.

A route with a parameter ($id, :id) reads it from E2E_<PARAM>; without it the test is skipped and the
surface is marked needs_fixture in plan.json, never dropped. Sign-in, when the owner grants E2E_USER and
E2E_PASSWORD (authorization.json -> env_allow), happens once in auth.setup.ts; no value is written here.
Every spec describes today's behaviour, not the intended one: a console error today is recorded, not fixed.
"""
import ast
import json
import re
from pathlib import Path

PAGE, HTTP = 'page', 'http'
PARAM = re.compile(r'\$(\w+)|:(\w+)')
SAFE = (ast.Import, ast.ImportFrom, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Assign, ast.AnnAssign)
REQUIREMENTS = 'approvaltests==19.1.1\npytest==9.1.1\n'

CONFIG = """import path from 'node:path';
import { defineConfig, devices } from '@playwright/test';

// Generated by EAOS. BASE_URL points at the running application; nothing here names a host.
export default defineConfig({
  testDir: './playwright',
  snapshotPathTemplate: '{testDir}/../__screenshots__/{testFilePath}/{arg}{ext}',
  reporter: [['json', { outputFile: 'results.json' }]],
  use: { baseURL: process.env.BASE_URL, storageState: path.join(__dirname, '.auth', 'user.json') },
  projects: [
    { name: 'setup', testMatch: /auth\\.setup\\.ts/ },
    { name: 'lock', dependencies: ['setup'], use: { ...devices['Desktop Chrome'] } },
  ],
});
"""

AUTH = """import fs from 'node:fs';
import path from 'node:path';
import { test as setup } from '@playwright/test';

// Generated by EAOS. Signs in once when the owner granted E2E_USER and E2E_PASSWORD; otherwise the lock
// runs signed out. E2E_LOGIN_PATH overrides the sign-in page when it is not /login.
const file = path.join(__dirname, '..', '.auth', 'user.json');

setup('sign in once, if credentials were granted', async ({ page }) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const user = process.env.E2E_USER;
  const password = process.env.E2E_PASSWORD;
  if (!user || !password) {
    fs.writeFileSync(file, JSON.stringify({ cookies: [], origins: [] }));
    setup.skip(true, 'no E2E_USER and E2E_PASSWORD: the lock runs signed out');
    return;
  }
  await page.goto(process.env.E2E_LOGIN_PATH ?? '/login');
  await page.locator('input[type="email"], input[name="email"], input[name="username"]').first().fill(user);
  await page.locator('input[type="password"]').first().fill(password);
  await page.locator('button[type="submit"], input[type="submit"]').first().click();
  await page.waitForLoadState('networkidle');
  await page.context().storageState({ path: file });
});
"""


def slug(text):
    return re.sub(r'[^a-z0-9]+', '-', str(text).lower()).strip('-') or 'root'


def surfaces(out):
    """{route: (surface kind, http method, file)} from the entry-point facts."""
    try: facts = json.loads((Path(out) / 'facts/entrypoints.json').read_text(encoding='utf-8'))['facts']
    except (OSError, ValueError, KeyError): return {}
    found = {}
    for fact in facts:
        value = fact.get('value') or {}
        if fact.get('kind') == 'entry_point' and value.get('route'):
            row = (value.get('surface'), (value.get('http_method') or 'GET').upper(), (fact.get('location') or {}).get('path'))
            found.setdefault(value['route'], row)
            # A command's feature names it by its file (run_app.py), not by its route (run_app).
            if value.get('surface') == 'cli' and row[2]: found.setdefault(row[2], row)
    return found


def kind_of(surface, known):
    """page, http or cli: from the entry-point facts; a surface they do not know is a page only if it is a URL."""
    if surface in known: return known[surface]
    return (PAGE if surface.startswith('/') or surface == '*' else 'cli', 'GET', None)


def path_of(route):
    """The URL a route id is served at, or None for a layout that has no URL of its own.

    TanStack Router ids name files, not URLs: a segment starting with `_` is a pathless layout and is not in
    the URL; a trailing `_` only un-nests the route (`cartoes_/faturas` is served at `/cartoes/faturas`);
    `(group)` segments (Next.js) are not in the URL either."""
    if route == '__root__': return None
    parts = [part for part in route.split('/') if part]
    if parts and parts[-1].startswith('_') and not parts[-1].startswith('__'): return None
    kept = [part.rstrip('_') if part.endswith('_') and not part.startswith('$') else part
            for part in parts if not (part.startswith('_') or (part.startswith('(') and part.endswith(')')))]
    return '/' + '/'.join(kept)


def url(route):
    """A route as a TypeScript template literal, parameters read from E2E_<PARAM>; and the parameters."""
    if route == '*': return '`/__eaos_unknown_route__`', []
    route = path_of(route) or route
    params = [a or b for a, b in PARAM.findall(route)]
    literal = PARAM.sub(lambda m: '${process.env.E2E_' + (m.group(1) or m.group(2)).upper() + " ?? ''}", route)
    return '`' + literal.replace('`', '\\`') + '`', params


def playwright_spec(feature, rows):
    """The spec text for a feature's pages and http routes, and the plan's surface list."""
    lines = ["import { test, expect } from '@playwright/test';", '',
             f"// Generated by EAOS from features.json: what \"{feature['name']}\" does today. The first run on the",
             '// original code records the snapshots; every later run must match them.', '',
             f"test.describe({json.dumps(feature['name'])}, () => {{"]
    listed = []
    for route, (kind, method, _) in rows:
        if route != '*' and path_of(route) is None:
            listed.append(f'{route} (layout: no URL of its own)')
            continue
        target, params = url(route)
        # Named by the URL, not the route id: moving a file between layouts must not orphan its recording.
        name = slug(path_of(route) or route) if route != '*' else 'unknown-route'
        guard = ''.join(f"  test.skip(!process.env.E2E_{p.upper()}, 'needs_fixture: set E2E_{p.upper()}');\n" for p in params)
        marker = ' (needs_fixture)' if params else ''
        if kind == HTTP and method != 'GET':
            listed.append(f'{method} {route} (needs_fixture: writes)')
            lines += [f"  test({json.dumps(f'{method} {route} is not called blindly')}, async () => {{",
                      f"    test.skip(true, 'needs_fixture: {method} writes; lock it against a fixture');", '  });']
            continue
        listed.append(('GET ' if kind == HTTP else '') + route + marker)
        if kind == HTTP:
            lines += [f"  test({json.dumps(f'GET {route} answers as it does today')}, async ({{ request }}) => {{",
                      *(f'  {g}' for g in guard.splitlines()),
                      f"    const response = await request.get({target});",
                      f"    expect(String(response.status())).toMatchSnapshot('{name}.status.txt');", '  });']
        else:
            lines += [f"  test({json.dumps(f'{route} renders as it does today')}, async ({{ page }}) => {{",
                      *(f'  {g}' for g in guard.splitlines()),
                      '    const messages: string[] = [];',
                      "    page.on('pageerror', (error) => messages.push(`pageerror: ${error.message}`));",
                      "    page.on('console', (message) => { if (message.type() === 'error') messages.push(`console: ${message.text()}`); });",
                      f'    await page.goto({target});',
                      "    await page.waitForLoadState('networkidle');",
                      f"    expect(messages.join('\\n')).toMatchSnapshot('{name}.console.txt');",
                      f"    await expect(page).toHaveScreenshot('{name}.png', {{ fullPage: true, maxDiffPixelRatio: 0.01 }});",
                      '  });']
    lines += ['});', '']
    return '\n'.join(lines), listed


def import_safe(path):
    """Whether importing the file only defines things: no top-level statement that runs code."""
    try: tree = ast.parse(Path(path).read_text(encoding='utf-8', errors='replace'))
    except (OSError, SyntaxError): return False
    for node in tree.body:
        if isinstance(node, SAFE): continue
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant): continue   # a docstring
        if isinstance(node, ast.If) and 'name' in ast.dump(node.test) and '__main__' in ast.dump(node.test): continue
        if isinstance(node, ast.Try) and all(isinstance(n, (ast.Import, ast.ImportFrom)) for n in node.body): continue
        return False
    return True


def approval_test(feature, target):
    modules = sorted({f[:-3].replace('/', '.') for f in feature.get('files') or []
                      if f.endswith('.py') and not f.split('/')[-1].startswith('test_') and import_safe(Path(target) / f)
                      and not f.endswith('__init__.py')})
    if not modules: return None, []
    text = '\n'.join([
        f'"""Generated by EAOS: the public interface of "{feature["name"]}" as it is today, approved on the original code."""',
        'import importlib', 'import inspect', '', 'from approvaltests import verify', '',
        f'MODULES = {json.dumps(modules, indent=4)}', '', '',
        'def public_interface():',
        '    lines = []',
        '    for name in MODULES:',
        '        module = importlib.import_module(name)',
        '        for attribute in sorted(n for n in vars(module) if not n.startswith("_")):',
        '            value = getattr(module, attribute)',
        '            if (inspect.isfunction(value) or inspect.isclass(value)) and getattr(value, "__module__", None) == name:',
        '                try: signature = str(inspect.signature(value))',
        '                except (TypeError, ValueError): signature = "(...)"',
        '                lines.append(f"{name}.{attribute}{signature}")',
        '    return "\\n".join(lines)', '', '',
        'def test_the_public_interface_is_as_it_was():',
        '    verify(public_interface())', ''])
    return text, modules


def build(out, target):
    """Write behavior-lock/ and return its plan (behavior-lock/plan.json, schemas/artifacts/behavior-lock-plan)."""
    out, target = Path(out), Path(target)
    try: features = json.loads((out / 'features.json').read_text(encoding='utf-8'))['features']
    except (OSError, ValueError, KeyError): features = []
    known = surfaces(out)
    root = out / 'behavior-lock'
    specs, wrote_playwright, wrote_python = [], False, False
    for feature in features:
        rows = [(route, kind_of(route, known)) for route in feature.get('surfaces') or []]
        web = [(route, info) for route, info in rows if info[0] in (PAGE, HTTP)]
        if web:
            text, listed = playwright_spec(feature, web)
            path = f'playwright/{slug(feature["name"])}.spec.ts'
            (root / path).parent.mkdir(parents=True, exist_ok=True)
            (root / path).write_text(text, encoding='utf-8')
            specs.append({'feature': feature['name'], 'tool': 'playwright', 'path': path, 'surfaces': listed})
            wrote_playwright = True
            continue
        text, modules = approval_test(feature, target)
        if text:
            path = f'approvals/test_{slug(feature["name"]).replace("-", "_")}.py'
            (root / path).parent.mkdir(parents=True, exist_ok=True)
            (root / path).write_text(text, encoding='utf-8')
            specs.append({'feature': feature['name'], 'tool': 'approvaltests', 'path': path, 'surfaces': modules})
            wrote_python = True
        else:
            specs.append({'feature': feature['name'], 'tool': 'approvaltests', 'path': '',
                          'surfaces': [f'{s} (needs_fixture: no web surface and no import-safe module)' for s in feature.get('surfaces') or []]})
    if wrote_playwright:
        (root / 'playwright.config.ts').write_text(CONFIG, encoding='utf-8')
        (root / 'playwright/auth.setup.ts').write_text(AUTH, encoding='utf-8')
    if wrote_python:
        (root / 'approvals/requirements.txt').write_text(REQUIREMENTS, encoding='utf-8')
    plan = {'schema_version': 1, 'specs': specs}
    if specs:
        root.mkdir(parents=True, exist_ok=True)
        (root / 'plan.json').write_text(json.dumps(plan, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
    return plan
