// The words of the Problems and Evidence pages, Arabic first and English equally finished. Kept with the pages; a
// key missing in one language is a type error.
import { makeWords } from '../../map/words'

export const PROBLEM_WORDS = {
  shownOf: ['{n} من {total}', '{n} of {total}'],
  filters: ['التصفية', 'Filter'],
  filtersN: ['التصفية ({n})', 'Filter ({n})'],
  filtersTitle: ['التصفية والتجميع', 'Filter and group'],
  groupBy: ['التجميع', 'Group by'],
  groupNone: ['بلا تجميع', 'No grouping'],
  group_area: ['المجال', 'Area'],
  group_component: ['المكوّن', 'Component'],
  group_step: ['خطوة الخطة', 'Plan step'],
  facet_severity: ['الشدة', 'Severity'],
  facet_area: ['المجال', 'Area'],
  facet_state: ['الحالة', 'State'],
  facet_step: ['خطوة الخطة', 'Plan step'],
  facet_component: ['المكوّن', 'Component'],
  clearAll: ['امسح التصفية', 'Clear filters'],
  removeFilter: ['أزل التصفية: {name}', 'Remove filter: {name}'],
  countsNote: ['كل رقم هنا هو عدد المشاكل التي ستظهر لو اخترته مع باقي التصفية، معدودة من بطاقات الفحص.', 'Each number is how many problems choosing it shows with the other filters, counted from the check\'s cards.'],
  showFacetAll: ['اعرض كل القيم ({n})', 'Show all values ({n})'],
  showMore: ['اعرض {n} أخرى', 'Show {n} more'],
  remaining: ['بقي {n}', '{n} left'],
  noComponent: ['بلا مكوّن', 'No component'],
  noStep: ['خارج الخطة', 'Not in the plan'],
  noArea: ['بلا مجال', 'No area'],
  newScan: ['وصل فحص جديد. القائمة ثابتة حتى تطلب التحديث.', 'A new check arrived. The list stays put until you ask.'],
  showChanges: ['اعرض التغييرات', 'Show changes'],
  area_security: ['الأمان', 'Security'],
  area_structure: ['البنية', 'Structure'],
  area_quality: ['جودة الكود', 'Code quality'],
  area_performance: ['الأداء', 'Performance'],
  area_maintainability: ['قابلية الصيانة', 'Maintainability'],
  // the detail
  whyItMatters: ['لماذا تهم', 'Why it matters'],
  place: ['المكان', 'Place'],
  component: ['المكوّن', 'Component'],
  area: ['المجال', 'Area'],
  kind: ['النوع', 'Kind'],
  confidence: ['الثقة', 'Confidence'],
  confirmed: ['مؤكدة', 'Confirmed'],
  likely: ['مرجّحة', 'Likely'],
  hypothesis: ['فرضية تحتاج تحققًا', 'A hypothesis to check'],
  confidenceSource: ['من درجة ثقة الادعاء في dossier.json', 'From the claim\'s confidence in dossier.json'],
  noConfidence: ['لم تُسجَّل', 'Not recorded'],
  inThePlan: ['موقعها في الخطة', 'Its place in the plan'],
  stepOf: ['الخطوة {step}', 'Step {step}'],
  taskOf: ['المهمة {k} من {n} في هذه الخطوة', 'Task {k} of {n} in this step'],
  notInPlan: ['ليست في خطة الإصلاح بعد.', 'Not in the fix plan yet.'],
  stepGate: ['تكتمل الخطوة حين:', 'The step is done when:'],
  operation: ['ما سيحدث للمكوّن', 'What happens to the component'],
  openTimeline: ['افتح الخطوة في الخطة', 'Open the step in the plan'],
  openOnMap: ['افتحه على الخريطة', 'Open it on the map'],
  sameFile: ['مشاكل أخرى في الملف نفسه', 'Other problems in the same file'],
  openEvidence: ['افتح الدليل', 'Open the evidence'],
  noEvidence: ['لا دليل مسجّل لهذه المشكلة في هذا التقرير.', 'This report records no evidence for this problem.'],
  evidenceMissing: ['الدليل {id} غير موجود في هذا التقرير.', 'The evidence {id} is not in this report.'],
  askAbout: ['اطلب من المساعد شرحها', 'Ask the assistant to explain it'],
  askRequest: ['اشرح لي المشكلة {id} من فحص EAOS: ما دليلها، ولماذا تهم، وماذا سيتغير لو أصلحناها.', 'Explain EAOS problem {id} to me: its evidence, why it matters, and what fixing it changes.'],
  // the code
  code: ['الكود', 'Code'],
  codeAt: ['الكود عند {where}', 'Code at {where}'],
  lineN: ['السطر {n}', 'Line {n}'],
  hiddenLine: ['أُخفي هذا السطر: فيه سرّ', 'Line hidden: it holds a secret'],
  noCodeSecret: ['لا يُعرض الكود: الدليل سرّ، ولا يُكتب السر في التقرير.', 'No code shown: the evidence is a secret, and a secret is never written to the report.'],
  noCodeLine: ['لم يسجّل المحرك سطرًا لهذا الدليل.', 'The engine recorded no line for this evidence.'],
  noCodeRead: ['لم يُقرأ الكود عند التصدير (الملف غير متاح أو فارغ).', 'The code was not read when the report was exported (the file was missing or empty).'],
  // the evidence page
  evidenceTitle: ['الدليل', 'Evidence'],
  engine: ['المحرك', 'Engine'],
  noEngine: ['فحص EAOS نفسه', 'EAOS\'s own check'],
  sites: ['أماكن أخرى ذكرها الدليل', 'Other places the evidence names'],
  citedBy: ['المشاكل التي تستند إليه', 'Problems that rest on it'],
  notCited: ['لا مشكلة في هذا التقرير تستند إلى هذا الدليل.', 'No problem in this report rests on this evidence.'],
  backToProblems: ['المشاكل', 'Problems'],
} as const

export type ProblemWord = keyof typeof PROBLEM_WORDS

export const useProblemWords = makeWords<ProblemWord>(PROBLEM_WORDS)
