// The words of the pipeline map, Arabic first and English equally finished. A key missing in one language is a type
// error. What EAOS wrote about the project (the verdict, a gap's detail, a router's condition) is shown as written.
import { useWordTable } from '../../map/words'
import type { Op, StageKind, View } from './model'

export const PIPELINE_WORDS = {
  pipeline: ['خط المعالجة', 'Pipeline'],
  pipelineLead: ['كيف تمرّ البيانات في المشروع: كل مرحلة وأدواتها، وما تأخذه وما تعطيه، والموجّهات وفروعها، ومسار الخطأ. كل عنصر بدليله في الكود، وما لم يتتبعه EAOS يظهر فجوة.',
    'How the data moves through the project: each stage and its tools, what it takes and gives, the routers and their branches, the failure route. Every element with its evidence in the code; what EAOS could not follow is drawn as a gap.'],
  view: ['ماذا يعرض الرسم', 'What the diagram shows'],
  view_current: ['الحالي', 'Current'],
  view_ideal: ['المثالي', 'Ideal'],
  view_gap: ['الفجوة', 'Gap'],
  showAs: ['طريقة العرض', 'Show as'],
  asMap: ['المخطط', 'Map'],
  asSteps: ['الخطوات', 'Steps'],
  showHidden: ['أظهر الخفي ({n})', 'Show hidden ({n})'],
  confidence: ['الثقة', 'Confidence'],
  counts: ['{s} مرحلة · {e} رابطًا · {g} فجوة', '{s} stages · {e} links · {g} gaps'],
  countsAria: ['خط المعالجة {t}: {s} مرحلة و{e} رابطًا', 'Pipeline {t}: {s} stages and {e} links'],
  pipelines: ['خطوط المعالجة', 'Pipelines'],
  subOf: ['داخل المرحلة {s}', 'inside stage {s}'],
  role_product: ['المنتج', 'product'],
  role_tooling: ['البناء والفحص', 'build and CI'],
  stagesN: ['{n} مرحلة', '{n} stages'],
  kind_stage: ['مرحلة', 'Stage'],
  kind_router: ['موجّه', 'Router'],
  kind_fork: ['تفرّع', 'Fork'],
  kind_join: ['تجميع', 'Join'],
  kind_ai: ['عقدة ذكاء اصطناعي', 'AI node'],
  kind_source: ['مصدر', 'Source'],
  kind_sink: ['مَصبّ', 'Sink'],
  kind_external: ['خارجي', 'External'],
  mark_slow: ['بطيئة', 'slow'],
  mark_risky: ['خطرة', 'risky'],
  mark_ai: ['نموذج', 'model'],
  mark_external: ['خارجية', 'external'],
  optional: ['اختيارية', 'optional'],
  takes: ['تأخذ', 'Takes'],
  gives: ['تعطي', 'Gives'],
  tools: ['الأدوات', 'Tools'],
  sideEffects: ['آثار جانبية', 'Side effects'],
  nothingDeclared: ['لا شيء معلن', 'nothing declared'],
  entry: ['المدخل', 'Entry'],
  symbol: ['الدالة', 'Function'],
  evidence: ['الدليل', 'Evidence'],
  branches: ['الفروع', 'Branches'],
  branchesN: ['{n} فرعًا', '{n} branches'],
  routesOn: ['يوجّه حسب', 'Routes on'],
  totalYes: ['كل قيمة لها فرع', 'every value has a branch'],
  totalNo: ['قيم بلا فرع: {v}', 'values with no branch: {v}'],
  totalUnknown: ['لا يعرف EAOS إن كانت كل قيمة لها فرع', 'EAOS cannot tell whether every value has a branch'],
  defaultBranch: ['الفرع الافتراضي', 'Default branch'],
  noTarget: ['بلا وجهة معروفة', 'no known target'],
  fanOut: ['يتفرّع إلى {n} فروع', 'Fans out to {n} branches'],
  fanIn: ['يجمعها: {s}', 'Gathered by: {s}'],
  fanNoJoin: ['لا شيء يجمع نتائجها', 'Nothing gathers their results'],
  control: ['التحكّم', 'Control'],
  control_loop: ['حلقة', 'loop'],
  control_retry: ['إعادة محاولة', 'retry'],
  control_conditional_skip: ['تخطٍّ بشرط', 'conditional skip'],
  control_early_exit: ['خروج مبكر', 'early exit'],
  failureLane: ['مسار الفشل', 'Failure lane'],
  failureRoutes: ['أين يذهب الفشل', 'Where failures go'],
  fromAny: ['من أي مرحلة', 'from any stage'],
  err_skip: ['تخطٍّ', 'skip'],
  err_fail: ['فشل', 'fail'],
  err_retry: ['إعادة', 'retry'],
  err_block: ['حجب ما بعدها', 'block what follows'],
  err_raise: ['رفع خطأ', 'raise'],
  err_catch: ['التقاط', 'catch'],
  err_fallback: ['بديل', 'fallback'],
  hidden: ['الخفي', 'Hidden'],
  hidden_side_channel: ['قناة جانبية', 'Side channel'],
  hidden_dead_stage: ['مرحلة لا يصلها شيء', 'Dead stage'],
  hidden_unread_output: ['مخرَج لا يقرؤه أحد', 'Unread output'],
  hiddenWhy: ['بيانات تمرّ خارج الروابط المعلنة، أو جزء لا يصله التشغيل: لا تظهر في المسار المعلن.', 'Data passing beside the declared links, or a part no run reaches: invisible in the declared flow.'],
  through: ['عبر {c}', 'through {c}'],
  unresolved: ['ما لم يتتبعه EAOS', 'What EAOS could not follow'],
  unresolvedLead: ['نداء لا يعرف EAOS إلى أين يذهب: يُرسم فجوة ويُعدّ، ولا يُخترع له رابط.', 'A call EAOS cannot follow: drawn as a gap and counted, never given an invented link.'],
  gapNode: ['لم يُتتبع', 'not followed'],
  links: ['الروابط', 'Links'],
  linkData: ['بيانات', 'data'],
  linkControl: ['تحكّم', 'control'],
  linkError: ['خطأ', 'error'],
  linkHidden: ['خفي', 'hidden'],
  matched_value: ['قيمة تُمرَّر', 'a value passed'],
  matched_file: ['ملف يُكتب ثم يُقرأ', 'a file written then read'],
  matched_table: ['جدول', 'a table'],
  matched_artifact: ['ناتج باسمه', 'a named artifact'],
  matched_topic: ['موضوع رسائل', 'a topic'],
  matched_declared: ['معلن في الكود', 'declared in the code'],
  matched_order: ['ترتيب التشغيل فقط', 'run order only'],
  howKnown: ['كيف عُرف', 'How it is known'],
  dataShape: ['شكل البيانات', 'Data shape'],
  comesFrom: ['يأتي من', 'Comes from'],
  goesTo: ['يذهب إلى', 'Goes to'],
  file: ['الملف', 'File'],
  fact: ['الحقيقة', 'Fact'],
  itsCards: ['بطاقاته ({n})', 'Its cards ({n})'],
  planSteps: ['خطوات الخطة', 'Plan steps'],
  codePath: ['مسار كودها', 'Its code path'],
  openCodePath: ['افتح مسار الكود عبر ملفها', 'Open the code paths through its file'],
  enter: ['ادخل خط معالجتها ({n})', 'Enter its pipeline ({n})'],
  back: ['ارجع إلى {t}', 'Back to {t}'],
  followData: ['اتبع البيانات', 'Follow the data'],
  followPick: ['اختر مدخلًا أو ناتجًا', 'Choose an input or an output'],
  followNone: ['بلا تتبّع', 'No trail'],
  followFrom: ['اتبع ما تعطيه', 'Follow what it gives'],
  followOn: ['مسار البيانات، من يكتبها وكل ما تصله بعده:', 'The data’s route, from who writes it to everything it reaches:'],
  clearFollow: ['أوقف التتبّع', 'Stop following'],
  ideal: ['المثالي', 'The ideal'],
  idealLead: ['المثالي مشتق من خط المعالجة نفسه بقواعد مذكورة المصدر. اللون العملية: يبقى، يُعدَّل، يُعاد بناؤه، يُدمج، يُحذف، جديد.',
    'The ideal is derived from this pipeline by rules, each with its source. Colour is the operation: keep, refactor, rebuild, merge, delete, new.'],
  idealBy_rules: ['صنعته القواعد', 'made by the rules'],
  idealBy_model: ['خطّطه نموذج فوق القواعد', 'planned by a model on top of the rules'],
  addedByIdeal: ['يضيفها المثالي', 'Added by the ideal'],
  addedNote: ['مراحل جديدة لا مكان لها اليوم: تُرسم بعد آخر طبقة.', 'New stages with no place today: drawn after the last layer.'],
  contract: ['العقد', 'Contract'],
  op_retain: ['يبقى', 'Keep'],
  op_refactor: ['يُعدَّل', 'Refactor'],
  op_rebuild: ['يُعاد بناؤه', 'Rebuild'],
  op_merge: ['يُدمج', 'Merge'],
  op_delete: ['يُحذف', 'Delete'],
  op_new: ['جديد', 'New'],
  rule: ['القاعدة', 'Rule'],
  source: ['المصدر', 'Source'],
  gap: ['الفجوة', 'The gap'],
  gapLead: ['مدخل لكل قاعدة مكسورة، بدليله وعمليته وبطاقته وخطوته في الخطة.', 'One entry per broken rule, with its evidence, its operation, its card and its plan step.'],
  gapEmpty: ['لا قاعدة مكسورة في خط المعالجة هذا.', 'No rule is broken in this pipeline.'],
  rules: ['القواعد', 'The rules'],
  brokenN: ['مكسورة {n}', 'broken {n}'],
  holds: ['تتحقق', 'holds'],
  subject: ['الموضوع', 'Subject'],
  card: ['البطاقة', 'Card'],
  step: ['الخطوة', 'Step'],
  noCard: ['لا بطاقة بعد', 'no card yet'],
  chooseStage: ['اختر مرحلة على المخطط لترى دليلها وما تأخذه وما تعطيه.', 'Choose a stage on the map to see its evidence and what it takes and gives.'],
  legend: ['مفتاح الرسم', 'Legend'],
  lgStage: ['مرحلة', 'stage'],
  lgRouter: ['موجّه بفروع مسماة', 'router, named branches'],
  lgAi: ['عقدة ذكاء اصطناعي', 'AI node'],
  lgFork: ['تفرّع وتجميع', 'fan-out and fan-in'],
  lgData: ['بيانات، وشكلها على الخط', 'data, its shape on the line'],
  lgControl: ['تحكّم أو ترتيب فقط', 'control or order only'],
  lgError: ['مسار الفشل', 'failure route'],
  lgHidden: ['قناة خفية', 'hidden channel'],
  lgDead: ['مرحلة لا يصلها شيء', 'dead stage'],
  lgGap: ['لم يتتبعه EAOS', 'not followed by EAOS'],
  lgSub: ['لها خط معالجة داخلي', 'has its own pipeline inside'],
  openDiagram: ['افتح المخطط كاملًا', 'Open the full map'],
  closeDiagram: ['أغلق المخطط', 'Close the map'],
  inspector: ['التفاصيل', 'Details'],
  layerN: ['الطبقة {n}', 'Layer {n}'],
  noPipeline: ['لم يجد EAOS خط معالجة في هذا المشروع', 'EAOS found no pipeline in this project'],
  noPipelineLead: ['هذا مشروع تطبيق لا خط معالجة: لا شيء في كوده يمرّر ناتج مرحلة إلى مرحلة تليها. لا يُرسم خط مخترع.',
    'This is an application, not a pipeline: nothing in its code passes one stage’s output to the next. No pipeline is invented.'],
  lookedFor: ['ما بحث عنه EAOS', 'What EAOS looked for'],
  found: ['وجد', 'found'],
  notFound: ['لم يجد', 'none'],
  absent: ['لا يحمل هذا التقرير خريطة خط المعالجة', 'This report has no pipeline map'],
  absentSub: ['الخريطة تُكتب من نتائج الفحص (facts/pipeline.json). أعد الفحص بنسخة EAOS أحدث لتظهر.',
    'The map is written from the scan (facts/pipeline.json). Check the project again with a newer EAOS to see it.'],
  pipelineMissing: ['خط المعالجة هذا غير موجود في هذا الفحص', 'This pipeline is not in this check'],
  partOfLong: ['يُرسم ما في الإطار فقط: اسحب على طول الخط، أو اختر مرحلة من الخطوات.', 'Only what is in view is drawn: pan along the line, or pick a stage from the steps.'],
  showAll: ['اعرض الكل ({n})', 'Show all ({n})'],
  seeGap: ['افتح الفجوة', 'Open the gap'],
  kindOf: ['نوعه: {k}', 'kind: {k}'],
  pk_declared_dag: ['سجل مراحل معلن', 'a declared stage registry'],
  pk_registry_loop: ['حلقة على سجل', 'a loop over a registry'],
  pk_orchestrator: ['منسّق يمرّر الناتج', 'an orchestrator passing outputs on'],
  pk_airflow: ['Airflow', 'Airflow'],
  pk_prefect: ['Prefect', 'Prefect'],
  pk_dagster: ['Dagster', 'Dagster'],
  pk_luigi: ['Luigi', 'Luigi'],
  pk_celery: ['سلاسل Celery', 'Celery chains'],
  pk_langgraph: ['رسم LangGraph', 'a LangGraph graph'],
  pk_n8n: ['تصدير n8n', 'an n8n export'],
  pk_node_red: ['تدفق Node-RED', 'a Node-RED flow'],
  pk_temporal: ['Temporal', 'Temporal workflows'],
  pk_step_functions: ['Step Functions', 'Step Functions'],
  pk_github_actions: ['مهام GitHub Actions', 'GitHub Actions jobs'],
  pk_makefile: ['أهداف Makefile', 'Makefile targets'],
  pk_justfile: ['أهداف justfile', 'justfile targets'],
  pk_npm_scripts: ['سلاسل سكربتات npm', 'npm script chains'],
  pk_queue: ['طوابير ومواضيع رسائل', 'queues and topics'],
  pk_cli_chain: ['أوامر تتسلسل', 'chained commands'],
  sheetTitle: ['ورقة خط المعالجة', 'Pipeline sheet'],
  aiNode: ['آخر قرار لهذه العقدة', "This node's last decision"],
  aiByModel: ['قرّرها {who} ({model})', 'Decided by {who} ({model})'],
  aiByRules: ['قُرّرت بالقواعد فقط', 'Decided by the rules only'],
  aiNotRun: ['ما اشتغلت هذه العقدة على هذا الفحص بعد. شغّلها من مركز التحكم («شغّل عُقد الذكاء»).', 'This node has not run on this check yet. Run it from the command centre ("Run the AI nodes").'],
  aiCached: ['من الذاكرة: المدخلات نفسها', 'from the cache: the same inputs'],
  aiAt: ['في {at}', 'at {at}'],
  aiCost: ['{s} ث · {c} دولار', '{s} s · {c} USD'],
  aiRoutes: ['أين ذهب العمل', 'Where the work went'],
  aiDropped: ['{n} قرارًا حُذف لأنه بلا دليل', '{n} decisions dropped for want of evidence'],
  aiQuestions: ['{n} سؤالًا ينتظرك في صندوق القرارات', '{n} questions wait for you in the Decisions inbox'],
  aiToInbox: ['افتح صندوق القرارات', 'Open the Decisions inbox'],
  aiLoading: ['يحمّل آخر قرار…', 'Loading the last decision…'],
  galleryPipeline: ['معرض خط المعالجة', 'Pipeline gallery'],
  galleryPipelineLead: ['المخطط والخطوات في العروض الثلاثة على بيانات EAOS الثابتة.', 'The map and the steps in the three views on the EAOS fixture.'],
} satisfies Record<string, readonly [string, string]>

export type PipelineWord = keyof typeof PIPELINE_WORDS

export const VIEW_WORD: Record<View, PipelineWord> = { current: 'view_current', ideal: 'view_ideal', gap: 'view_gap' }
export const OP_WORD: Record<Op, PipelineWord> = { retain: 'op_retain', refactor: 'op_refactor', rebuild: 'op_rebuild', merge: 'op_merge', delete: 'op_delete', new: 'op_new' }
export const KIND_WORD: Record<StageKind, PipelineWord> = {
  stage: 'kind_stage', router: 'kind_router', fork: 'kind_fork', join: 'kind_join', ai: 'kind_ai', source: 'kind_source', sink: 'kind_sink', external: 'kind_external',
}

/** A word looked up by a key the data writes ("err_" + "skip"), or the data's own word when the catalogue has none. */
export function usePipelineWords() {
  const w = useWordTable(PIPELINE_WORDS)
  const known = (prefix: string, key: string) => (`${prefix}${key}` in PIPELINE_WORDS ? w(`${prefix}${key}` as PipelineWord) : key.replace(/_/g, ' '))
  return Object.assign(w, { known })
}
