// The words of Change: the Bridge, the gap register, the plans and their steps, tasks and operations. Arabic first
// and English equally finished; a key missing in one language is a type error. Counts stand after a label ("الملفات: 12")
// so no Arabic noun has to agree with a number.
import { makeWords } from '../../map/words'
import type { ChangeOp, OpState } from '../../data/change'

export const CHANGE_WORDS = {
  changeNav: ['أقسام التغيير', 'Change sections'],
  navOverview: ['نظرة عامة', 'Overview'],
  navBridge: ['الجسر', 'Bridge'],
  navGaps: ['الفجوات', 'Gaps'],
  navPlans: ['الخطط', 'Plans'],
  today: ['اليوم', 'Today'],
  target: ['الهدف', 'Target'],
  files: ['الملفات', 'Files'],
  filesN: ['الملفات: {n}', 'Files: {n}'],
  cardsN: ['البطاقات: {n}', 'Cards: {n}'],
  notMeasured: ['لم يُقس بعد', 'Not measured yet'],
  sep: ['، ', ', '],
  showAs: ['طريقة العرض', 'Show as'],
  asDiagram: ['الرسم', 'Diagram'],
  asTable: ['الجدول', 'Table'],

  bridgeTitle: ['أين يذهب كل جزء', 'Where each part goes'],
  bridgeLead: ['كل مكوّن في الكود اليوم وإلى أين ينتقل في الصورة المستهدفة. عرض الشريط بعدد ملفاته، ولونه العملية.',
    'Each component of the code today and where it goes in the target. A ribbon is as wide as its files and coloured by its operation.'],
  bridgeAria: ['الجسر: {c} مكوّنًا اليوم تنتقل إلى {t} مكوّنات في الهدف', 'The Bridge: {c} components of today going to {t} components of the target'],
  ribbonAria: ['{from}، الملفات: {n}، {op}، إلى {to}', '{from}, {n} files, {op}, to {to}'],
  removed: ['يُحذف', 'Removed'],
  other: ['أخرى ({n})', 'Other ({n})'],
  otherAria: ['مكوّنات صغيرة أخرى: {n}', '{n} other small components'],
  newHere: ['جديد', 'New'],
  todaySummary: ['اليوم', 'Today'],
  todayLine: ['مكوّنات الكود: {c} · ملفاتها: {f} · يُحذف منها: {d}', 'Components in the code: {c} · their files: {f} · removed: {d}'],
  targetLine: ['مكوّنات الهدف: {t} · يجمع كلٌّ منها أكثر من مكوّن: {m} · جديدة: {n}', 'Target components: {t} · each gathering several of today’s: {m} · new: {n}'],
  targetSummary: ['الهدف', 'The target'],
  goesTo: ['إلى', 'Goes to'],
  fromComponent: ['من', 'From'],
  transferLead: ['كل مكوّن في الهدف، وما ينتقل إليه من الكود اليوم.', 'Each component of the target, and what moves into it from the code today.'],
  opMix: ['مزيج العمليات', 'Operation mix'],
  noTarget: ['لا صورة مستهدفة في هذا الفحص', 'This check has no target picture'],
  noTargetSub: ['الجسر يحتاج البنية المستهدفة، وهذا الفحص لم يحسبها.', 'The Bridge needs the target structure, and this check did not compute it.'],

  gapsTitle: ['سجل الفجوات', 'Gap register'],
  gapsLead: ['ما يفصل كل مكوّن عن الصورة المثالية، والعملية التي تسدّه، وكم أغلقت منه بطاقاته.',
    'What separates each component from the ideal, the operation that closes it, and how much of it its cards have closed.'],
  gapsCount: ['الفجوات: {n} · لها بطاقات: {c} · بلا بطاقة بعد: {u}', 'Gaps: {n} · with cards: {c} · no card yet: {u}'],
  byOperation: ['حسب العملية', 'By operation'],
  allOps: ['الكل ({n})', 'All ({n})'],
  opCount: ['{op} ({n})', '{op} ({n})'],
  colComponent: ['المكوّن', 'Component'],
  colOperation: ['العملية', 'Operation'],
  colTo: ['إلى', 'To'],
  colClosed: ['ما أُغلق ببطاقاته', 'Closed by its cards'],
  colSteps: ['الخطوات', 'Steps'],
  colDecision: ['القرار', 'Decision'],
  closedOf: ['{c} من {n}', '{c} of {n}'],
  noCard: ['لا بطاقة تسدّها بعد', 'No card closes it yet'],
  stays: ['يبقى كما هو', 'Stays as it is'],
  noGapsShown: ['لا فجوة بهذه العملية', 'No gap with this operation'],
  gapNotFound: ['هذه الفجوة ليست في هذا الفحص', 'This gap is not in this check'],
  why: ['لماذا هذه العملية', 'Why this operation'],
  responsibility: ['مسؤوليته في الهدف', 'Its responsibility in the target'],
  cover: ['تغطية البطاقات', 'Card coverage'],
  cover_covered: ['البطاقات تغطيها', 'Covered by cards'],
  cover_partial: ['البطاقات تغطي جزءًا منها', 'Partly covered by cards'],
  cover_missing: ['لا بطاقة تغطيها', 'No card covers it'],
  closesIt: ['البطاقات التي تسدّها', 'The cards that close it'],
  operations: ['العمليات', 'Operations'],
  planSteps: ['خطوات الخطة', 'Plan steps'],
  decision: ['قرار البنية', 'Structure decision'],
  openDecisions: ['افتح القرارات', 'Open the decisions'],
  openOnMap: ['افتحه على الخريطة', 'Open it on the map'],
  sources: ['المكوّنات التي تُدمج فيه', 'The components merged into it'],
  closedSrc: ['المصدر: {src}', 'Source: {src}'],

  plansTitle: ['الخطط', 'Plans'],
  plansLead: ['كل خطة بخطواتها، وتقدّمها من سجل الإنجاز وحده.', 'Every plan with its steps; progress comes only from the ledger.'],
  noPlans: ['لا خطة في هذا الفحص', 'This check has no plan'],
  planNotFound: ['هذه الخطة ليست في هذا الفحص', 'This plan is not in this check'],
  notStarted: ['لم تبدأ', 'Not started'],
  donePct: ['أُنجز {p}٪', '{p}% done'],
  stepsN: ['الخطوات: {n}', 'Steps: {n}'],
  tasksN: ['المهام: {n}', 'Tasks: {n}'],
  opsN: ['العمليات: {n}', 'Operations: {n}'],
  planState: ['حالة الخطة', 'Plan state'],
  ps_registered: ['مسجّلة', 'Registered'],
  ps_approved: ['معتمدة', 'Approved'],
  ps_active: ['قيد التنفيذ', 'Active'],
  ps_review: ['قيد المراجعة', 'In review'],
  ps_merged: ['مدموجة', 'Merged'],
  ps_closed: ['مغلقة', 'Closed'],
  planView: ['طريقة عرض الخطة', 'Plan view'],
  viewTimeline: ['الخط الزمني', 'Timeline'],
  viewGraph: ['الاعتماديات', 'Dependencies'],
  viewBoard: ['العمليات', 'Operations'],
  timelineLead: ['الخطوات بترتيبها. الشريط يعدّ مهام كل خطة حسب حالتها في سجل الإنجاز.',
    'The steps in order. Each bar counts the step’s tasks by their state in the ledger.'],
  waitsFor: ['تنتظر', 'Waits for'],
  comesBefore: ['تسبق', 'Comes before'],
  waitsNone: ['لا تنتظر خطوة أخرى', 'Waits for no other step'],
  waitsHow: ['{n} مهام تنتظر', '{n} waiting tasks'],
  wavesSpan: ['الموجات {a}–{b}', 'Waves {a}–{b}'],
  waveOne: ['الموجة {a}', 'Wave {a}'],
  openWaveGrid: ['افتح جدول الموجات', 'Open the wave grid'],
  graphLead: ['سهم من خطوة إلى أخرى يعني أن مهمة في الثانية تنتظر مهمة في الأولى: متطلّبًا سابقًا أو الملف نفسه. الرقم عدد المهام المنتظرة.',
    'An arrow from one step to another means a task of the second waits for a task of the first: a prerequisite or the same file. The number counts the waiting tasks.'],
  graphNone: ['لا تنتظر أي خطوة خطوة أخرى في هذه الخطة.', 'No step of this plan waits for another.'],
  graphAria: ['اعتماديات الخطوات: {n} سهمًا', 'Step dependencies: {n} arrows'],
  edgeAria: ['{to} تنتظر {from}: {n}', '{to} waits for {from}: {n}'],
  boardLead: ['العمليات بترتيب تنفيذها، في مسار لكل نوع. الرقم ترتيب العملية في الخطة.',
    'The operations in the order they run, one lane per kind. The number is the operation’s place in the plan.'],
  noOps: ['لا عمليات في هذا الفحص', 'This check has no operations'],
  notPlanned: ['ليست في خطوة من الخطة', 'Not in a step of the plan'],
  st_todo: ['لم تبدأ', 'To do'],
  st_active: ['قيد العمل', 'In progress'],
  st_done: ['منجزة', 'Done'],
  st_blocked: ['متوقفة', 'Blocked'],
  st_regressed: ['تراجعت', 'Regressed'],
  stateCounts: ['حالات المهام', 'Task states'],

  stepNotFound: ['هذه الخطوة ليست في الخطة', 'This step is not in the plan'],
  stepKicker: ['الخطوة {id}', 'Step {id}'],
  gate: ['شرط إغلاقها', 'Its exit gate'],
  stepTasks: ['مهامها', 'Its tasks'],
  stepOps: ['عملياتها', 'Its operations'],
  stepRequest: ['ابدأ دفعة إصلاح لبطاقات الخطوة {id} من خطة الإصلاح، بالأداة fix_start.',
    'Start a fix batch for the cards of step {id} of the fix plan, with the fix_start tool.'],
  copyStep: ['انسخ طلب هذه الخطوة', 'Copy this step’s request'],

  taskNotFound: ['هذه المهمة ليست في هذا الفحص', 'This task is not in this check'],
  taskKicker: ['المهمة', 'Task'],
  inStep: ['في الخطوة', 'In step'],
  wave: ['الموجة', 'Wave'],
  state: ['الحالة', 'State'],
  severity: ['الخطورة', 'Severity'],
  taskWaits: ['ما تنتظره', 'What it waits for'],
  taskWaitsNone: ['لا تنتظر مهمة أخرى', 'It waits for no other task'],
  why_prerequisite: ['متطلّب سابق', 'prerequisite'],
  why_same_file: ['الملف نفسه', 'same file'],
  partOf: ['ضمن العمليات', 'Part of the operations'],
  openProblem: ['افتح المشكلة', 'Open the problem'],

  opNotFound: ['هذه العملية ليست في هذا الفحص', 'This operation is not in this check'],
  opKicker: ['عملية {n} من {t}', 'Operation {n} of {t}'],
  subject: ['على', 'On'],
  after: ['تأتي بعد', 'Comes after'],
  before: ['تأتي قبل', 'Comes before'],
  afterNone: ['لا تنتظر عملية أخرى', 'Waits for no other operation'],
  afterHow: ['مهمة من هذه العملية تنتظر مهمة من تلك: متطلّبًا سابقًا أو الملف نفسه.',
    'A task of this operation waits for a task of that one: a prerequisite or the same file.'],
  itsGap: ['فجوتها', 'Its gap'],
  itsCards: ['بطاقاتها', 'Its cards'],
  noCards: ['لا بطاقة لهذه العملية بعد', 'No card for this operation yet'],
} as const

export type ChangeWord = keyof typeof CHANGE_WORDS
export const useChangeWords = makeWords<ChangeWord>(CHANGE_WORDS)

export const STATE_WORD: Record<OpState, ChangeWord> = { todo: 'st_todo', active: 'st_active', done: 'st_done', blocked: 'st_blocked', regressed: 'st_regressed' }
export const OPS: ChangeOp[] = ['delete', 'refactor', 'rebuild', 'merge', 'new', 'retain']
