// The words of the live check, Arabic first and English equally finished. A key missing in one language is a type
// error. The stages themselves come from EAOS (eaos/pipeline/stages.py, through the progress file): a stage this table
// does not know yet is shown by its own name and description, so a new stage appears with no change here.
import { makeWords } from '../../map/words'

export const SCAN_WORDS = {
  title: ['الفحص الآن', 'Live check'],
  lead: ['مراحل فحص EAOS كما تجري الآن: المرحلة التي تعمل تتوهّج، وحين تنتهي ينتقل الضوء إلى المراحل التي بعدها. اضغط أي مرحلة لترى ما تفعله وما أنتجته.',
    'EAOS\'s own stages as the check runs: the running stage glows, and when it ends the light travels on to the stages after it. Select any stage to see what it does and what it produced.'],
  run_none: ['لا يوجد فحص بعد', 'No check yet'],
  run_running: ['الفحص يعمل', 'Check running'],
  run_done: ['انتهى الفحص', 'Check finished'],
  run_interrupted: ['توقّف الفحص قبل أن ينتهي', 'The check stopped before it ended'],
  status_COMPLETE: ['مكتمل', 'complete'],
  status_PARTIAL: ['جزئي', 'partial'],
  status_INCOMPLETE: ['ناقص', 'incomplete'],
  status_ERROR: ['تعطّل', 'broke'],
  status_STOPPED: ['أُوقف', 'stopped'],
  stageOf: ['المرحلة {n} من {t}', 'Stage {n} of {t}'],
  endedOf: ['{n} من {t} مرحلة', '{n} of {t} stages'],
  elapsed: ['مضى', 'Elapsed'],
  took: ['استغرق', 'Took'],
  left: ['يتبقّى نحو {m} دقيقة', 'about {m} min left'],
  leftLess: ['يتبقّى أقل من دقيقة', 'under a minute left'],
  leftWhy: ['تقدير من مدة آخر فحص لهذا المشروع، مرحلة مرحلة', 'An estimate from the last check of this project, stage by stage'],
  firstRun: ['أول فحص: لا تقدير للوقت المتبقي', 'First check: no estimate of the time left'],
  started: ['بدأ', 'Started'],
  state_waiting: ['تنتظر', 'Waiting'],
  state_running: ['تعمل الآن', 'Running'],
  state_ok: ['تمّت', 'Done'],
  state_skipped: ['لم تُطلب', 'Not asked'],
  state_unavailable: ['غير متاحة', 'Unavailable'],
  state_failed: ['فشلت', 'Failed'],
  state_not_reached: ['لم تُبلغ', 'Not reached'],
  state_stopped: ['توقّفت', 'Stopped'],
  step_waiting: ['تنتظر', 'waiting'],
  step_running: ['تعمل', 'running'],
  step_ok: ['تمّت', 'done'],
  step_observed: ['اشتغلت', 'ran'],
  step_unavailable: ['غير مثبتة', 'not installed'],
  step_not_applicable: ['لا تنطبق', 'not applicable'],
  step_error: ['خطأ', 'error'],
  map: ['خريطة مراحل الفحص', 'Map of the check\'s stages'],
  mapAria: ['خريطة مراحل الفحص: {n} مرحلة. {s}', 'Map of the check\'s stages: {n} stages. {s}'],
  follow: ['تابع المرحلة الجارية', 'Follow the running stage'],
  stages: ['المراحل', 'Stages'],
  whatItDoes: ['ماذا تفعل', 'What it does'],
  needs: ['تحتاج', 'Needs'],
  needsNothing: ['لا شيء: هي البداية', 'Nothing: it is the start'],
  necessity: ['ضرورتها', 'Necessity'],
  required: ['ضرورية', 'Required'],
  optional: ['اختيارية', 'Optional'],
  absentWhen: ['قد تغيب حين', 'May be absent when'],
  time: ['الوقت', 'Time'],
  lastTime: ['آخر مرة: {t}', 'Last time: {t}'],
  steps: ['خطواتها', 'Its steps'],
  stepsOf: ['{d} من {t}', '{d} of {t}'],
  produced: ['ما أنتجته', 'What it produced'],
  producesWhenDone: ['ستنتج', 'Will produce'],
  producedNothing: ['لم تنتج شيئًا في هذا الفحص', 'Produced nothing in this check'],
  reported: ['ما أبلغت عنه', 'What it reported'],
  why: ['السبب', 'Why'],
  keptFromBefore: ['أُخذت كما هي من فحص سابق لم يكتمل', 'Kept as it was from an earlier check that did not finish'],
  noneTitle: ['لم يسجّل EAOS تقدّم أي فحص هنا بعد', 'EAOS has not recorded the progress of a check here yet'],
  noneSub: ['ابدأ فحصًا (من المساعد، أو eaos start، أو من هنا) وستظهر مراحله هنا وهي تجري. الفحوص التي سبقت هذه الميزة لا تظهر.',
    'Start a check (from the assistant, eaos start, or from here) and its stages show here as they run. Checks made before this feature do not show.'],
  snapshotTitle: ['الخريطة الحية تعمل في الاستوديو الحي فقط', 'The live map works in the live Studio only'],
  snapshotSub: ['هذه نسخة ثابتة من التقرير. افتح الاستوديو الحي (eaos studio، أو اطلب من مساعدك open_studio) لترى الفحص وهو يجري.',
    'This is a fixed copy of the report. Open the live Studio (eaos studio, or ask your assistant for open_studio) to watch the check as it runs.'],
  loading: ['يقرأ تقدّم الفحص…', 'Reading the check\'s progress…'],
  interruptedSub: ['العملية التي كانت تشغّل الفحص لم تعد تعمل. ما تمّ قبل توقّفها محفوظ؛ ابدأ الفحص من جديد ليكمل.',
    'The process that ran the check is gone. What finished before it stopped is kept; start the check again to finish it.'],
  banner: ['فحص يعمل الآن: {s}', 'A check is running: {s}'],
  bannerOf: ['({n} من {t})', '({n} of {t})'],
  watch: ['شاهده', 'Watch it'],
  announceEnded: ['انتهت مرحلة {s}: {w}', 'Stage {s} ended: {w}'],
  announceRun: ['انتهى الفحص: {w}', 'The check ended: {w}'],
  legend: ['دليل الألوان', 'Legend'],
  // when an optional stage may be absent (eaos/pipeline/stages.py absent_when), in plain words
  absent_lock: ['حين لا يملك البرنامج ميزة تُثبَّت', 'when the program has no feature to lock'],
  absent_engines: ['حين لا تكون أي أداة خارجية مثبتة، أو لم تُطلب الأدوات', 'when no external tool is installed, or the tools were not asked for'],
  absent_verify: ['حين لا يُعطى أمر الاختبارات، أو لم يُسمح بالتشغيل', 'when no test command was given, or running was not allowed'],
  absent_policy: ['حين لا يعلن المشروع ملف eaos.policy.json', 'when the project declares no eaos.policy.json'],
  absent_semantic: ['حين لا يُضبط مزوّد نموذج', 'when no model provider was configured'],
  absent_quality: ['حين لا تكون Vale ولا markdownlint مثبتة', 'when neither Vale nor markdownlint is installed'],
  absent_pdf: ['حين لا تكون Typst أو خط لغة التقرير مثبتة', 'when Typst, or a font for the report language, is not installed'],
  absent_emit: ['حين لا تنطبق أي صيغة أداة', 'when no tool format applies'],
  absent_site: ['حين يُطلب الفحص بلا صفحة تصفح', 'when the check was asked for without the browsable page'],
  // the stages EAOS declares today; a new one shows by its own name until it has words here
  stage_facts: ['قراءة الكود', 'Read the code'],
  about_facts: ['يقرأ كل ملفات المشروع ويستخرج منها الحقائق، دون تشغيل شيء.', 'Reads every file of the project and extracts its facts, running nothing.'],
  stage_features: ['ما يفعله البرنامج', 'Features'],
  about_features: ['يجمع نقاط الدخول والوصول إلى البيانات في ميزات يفهمها المستخدم.', 'Groups entry points and data accesses into what the program does for a user.'],
  stage_lock: ['تثبيت السلوك', 'Behaviour lock'],
  about_lock: ['مواصفة لكل ميزة تصف ما يفعله النظام اليوم، قبل أي تغيير.', 'A spec per feature describing what the system does today, before any change.'],
  stage_intake: ['ما يجب حمايته', 'What to protect'],
  about_intake: ['إجاباتك، أو الافتراضات المعلنة، وسيناريوهات الجودة.', 'Your answers, or the declared defaults, and the quality scenarios.'],
  stage_engines: ['الأدوات الخارجية', 'External tools'],
  about_engines: ['أدوات فحص معروفة بنسخ مثبّتة، تُجمع نتائجها في مجموعة حقائق واحدة.', 'Well-known analyzers at pinned versions, their results joined into one fact set.'],
  stage_verify: ['تشغيل الاختبارات', 'Run the tests'],
  about_verify: ['يشغّل اختبارات المشروع في نسخة معزولة ويقيس ما تغطيه فعلًا.', 'Runs the project\'s tests in an isolated copy and measures what they really cover.'],
  stage_measure: ['القياس', 'Measure'],
  about_measure: ['صف لكل ملف: الحجم والتعقيد والتكرار والتغيير والاعتماد، كل رقم بمصدره.', 'One row per file: size, complexity, duplication, change and dependency, each with its source.'],
  stage_policy: ['قواعد البنية', 'Architecture rules'],
  about_policy: ['يطبّق قواعد البنية التي أعلنها المشروع.', 'Enforces the architecture rules the project declares.'],
  stage_load: ['نموذج الحمل', 'Load model'],
  about_load: ['تكلفة كل نقطة دخول، مع توقّع معلن عند ألف ضعف.', 'A cost record per entry point, with a stated projection at 1000x.'],
  stage_claims: ['الادعاءات', 'Claims'],
  about_claims: ['تُفسَّر الحقائق إلى سجل ادعاءات يمكن إثبات خطئها.', 'The facts interpreted into a ledger of claims that can be proven wrong.'],
  stage_probe: ['التحقق الآلي', 'Probes'],
  about_probe: ['يحسم كل ادعاء يمكن التحقق منه آليًا.', 'Settles every claim that can be decided mechanically.'],
  stage_semantic: ['قراءة النموذج', 'Model reading'],
  about_semantic: ['قراءة نموذج ذكاء اصطناعي فوق الحقائق؛ كل ما يخرج منها يبقى فرضية.', 'A model\'s reading over the facts; everything it says stays a hypothesis.'],
  stage_sustainability: ['الاستدامة', 'Sustainability'],
  about_sustainability: ['مؤشرات الاستدامة الستة، مقيسة أو معلنة غير مقيسة.', 'The six sustainability indicators, measured or declared unmeasured.'],
  stage_transform: ['خطة التحويل', 'Transform plan'],
  about_transform: ['بيت واحد لكل تعريف متكرر، والنقلة التي توصل إليه.', 'One home for each repeated definition, and the move that gets there.'],
  stage_plan: ['الخطة', 'Plan'],
  about_plan: ['الادعاءات المؤكدة تصير بطاقات مهام مرتبة في دفعات.', 'Confirmed claims become task cards ordered into batches.'],
  stage_target: ['البنية المستهدفة', 'Target architecture'],
  about_target: ['جرد المصدر وقرارات الهدف المراجَعة؛ المجهول يبقى فجوة.', 'The source inventory and reviewed target decisions; what is unknown stays a gap.'],
  stage_reports: ['التقارير الأربعة', 'The four reports'],
  about_reports: ['التقارير الأربعة التي تُقرأ أولًا؛ كل ما سواها ملحق بها.', 'The four reports read first; every other document is an appendix to them.'],
  stage_quality: ['جودة التقرير', 'Report quality'],
  about_quality: ['أداتا Vale وmarkdownlint تحكمان على أسلوب التقارير وبنيتها.', 'Vale and markdownlint judge the reports\' style and structure.'],
  stage_pdf: ['ملخص PDF', 'PDF summary'],
  about_pdf: ['الملخص التنفيذي في صفحة واحدة، بصيغة PDF.', 'The one-page executive summary, as a PDF.'],
  stage_execution_guide: ['دليل التنفيذ', 'Execution guide'],
  about_execution_guide: ['تعليمات تنفيذ حرفية ومرتبة لكل بطاقة مهمة.', 'Literal, ordered instructions for every task card.'],
  stage_executive: ['الملخص التنفيذي', 'Executive view'],
  about_executive: ['المؤشرات المقيسة وحدودها، في نظرة واحدة.', 'The measured indicators and their limits, at a glance.'],
  stage_compose: ['صفحات القراءة', 'Pages to read'],
  about_compose: ['المستندات التي يقرؤها الإنسان، كل منها في حدّه من الأسطر.', 'The documents a person reads, each within its line budget.'],
  stage_bundles: ['الحزم', 'Bundles'],
  about_bundles: ['يحزم التقرير نفسه في ملفاته، مع الحفاظ على عقد العمل.', 'Packages the same report into its files, keeping the engagement contract.'],
  stage_emit: ['ملفات الأدوات', 'Tool files'],
  about_emit: ['ملفات بصيغ أدوات أخرى، تحكم على كل منها أداتها.', 'Files in other tools\' own formats, each judged by its own tool.'],
  stage_site: ['صفحة التصفح', 'Browsable page'],
  about_site: ['صفحة واحدة تتصفح فيها السجلات نفسها.', 'One page to browse the same records.'],
  stage_validate: ['التحقق الأخير', 'Final check'],
  about_validate: ['يكتب ما فعله الفحص وما لم يفعله، ثم يحكم على المخرجات.', 'Writes what the run did and did not do, then judges the output.'],
} satisfies Record<string, readonly [string, string]>

export type ScanWord = keyof typeof SCAN_WORDS

const base = makeWords<ScanWord>(SCAN_WORDS)

/** The words, and the two lookups by a key the data writes: a stage's title and what it does, a state, a step. */
export function useScanWords() {
  const w = base()
  const has = (key: string): key is ScanWord => key in SCAN_WORDS
  const stageTitle = (name: string) => (has(`stage_${name}`) ? w(`stage_${name}` as ScanWord) : name.replace(/_/g, ' '))
  const about = (name: string, fallback: string) => (has(`about_${name}`) ? w(`about_${name}` as ScanWord) : fallback)
  const absent = (name: string, fallback: string) => (has(`absent_${name}`) ? w(`absent_${name}` as ScanWord) : fallback)
  const known = (prefix: string, key: string | null | undefined) => (key && has(`${prefix}${key}`) ? w(`${prefix}${key}` as ScanWord) : (key ?? '').replace(/_/g, ' '))
  return Object.assign(w, { stageTitle, about, absent, known })
}
