// The words of the function explorer, Arabic first and English equally finished. A key missing in one language is a
// type error.
import { makeWords } from '../../map/words'

export const FUNCTION_WORDS = {
  functions: ['الدوال', 'Functions'],
  lead: ['{f} دالة في {m} ملفًا. تتبّع EAOS {c} استدعاءً بينها، و{d} دالة منها تقرأ بيانات أو تكتبها.', '{f} functions in {m} files. EAOS traced {c} calls between them, and {d} of them read or write data.'],
  leadNone: ['لم يجد EAOS دوال في الملفات التي قرأها.', 'EAOS found no functions in the files it read.'],
  coverageTitle: ['ما قاسه EAOS لكل لغة', 'What EAOS measured per language'],
  lang_measured: ['مقيسة مع استدعاءاتها', 'measured with their calls'],
  lang_partial: ['بلا تتبع للاستدعاءات', 'calls not traced'],
  lang_not_measured: ['لم تُقس بعد', 'not measured yet'],
  lang_empty: ['لا دوال', 'no functions'],
  lang_failed: ['تعذّر القياس', 'could not be measured'],
  byStep: ['تأتي بها الخطوة', 'Comes with step'],
  search: ['ابحث في الدوال', 'Search functions'],
  searchHint: ['اسم دالة أو ملف أو جدول', 'A function, file or table'],
  sortBy: ['الترتيب', 'Order'],
  sort_risk: ['الأعقد', 'Most complex'],
  sort_callers: ['الأكثر استدعاءً', 'Most called'],
  sort_size: ['الأطول', 'Longest'],
  sort_name: ['بالاسم', 'By name'],
  showWhich: ['أي الدوال', 'Which functions'],
  show_all: ['الكل', 'All'],
  show_problems: ['عليها مشاكل', 'With problems'],
  show_data: ['تلمس البيانات', 'Touch data'],
  show_unused: ['لا أحد يستدعيها', 'Called by none'],
  kindFilter: ['النوع', 'Kind'],
  anyKind: ['كل الأنواع', 'Any kind'],
  kind_function: ['دالة', 'Function'],
  kind_method: ['دالة داخلية', 'Inner function'],
  kind_component: ['مكوّن واجهة', 'UI component'],
  kind_hook: ['خطاف React', 'React hook'],
  kind_handler: ['معالج حدث', 'Event handler'],
  kind_class: ['صنف', 'Class'],
  kinds_component: ['المكوّنات', 'Components'],
  kinds_hook: ['الخطافات', 'Hooks'],
  kinds_handler: ['المعالجات', 'Handlers'],
  kinds_function: ['الدوال', 'Functions'],
  kinds_method: ['الداخلية', 'Inner'],
  inFile: ['في الملف', 'In the file'],
  clearFile: ['أزل تصفية الملف', 'Clear the file filter'],
  shown: ['{n} من {t}', '{n} of {t}'],
  showMore: ['اعرض {n} أخرى', 'Show {n} more'],
  noMatch: ['لا دالة تطابق هذا البحث', 'No function matches'],
  noMatchSub: ['جرّب كلمة أخرى أو أزل التصفية.', 'Try another word or clear the filters.'],
  clearAll: ['أزل كل التصفية', 'Clear all filters'],
  complexityShort: ['تعقيد {n}', 'complexity {n}'],
  callersShort: ['{n} يستدعيها', '{n} callers'],
  problemsShort: ['{n} مشكلة', '{n} problems'],
  problemShort: ['مشكلة واحدة', '1 problem'],
  // overview pane (desktop)
  overview: ['نظرة على الدوال', 'The functions at a glance'],
  overviewSub: ['اختر دالة من القائمة لترى ما تفعله ومن يستدعيها وما تلمسه.', 'Choose a function in the list to see what it does, who calls it and what it touches.'],
  riskiest: ['الأعقد', 'The most complex'],
  mostCalled: ['الأكثر استدعاءً', 'The most called'],
  withProblems: ['عليها مشاكل', 'With problems'],
  // detail
  notFound: ['هذه الدالة ليست في هذا الفحص', 'This function is not in this check'],
  notFoundSub: ['ربما حُذفت أو تغيّر اسمها منذ الرابط. افتح قائمة الدوال.', 'It may have been removed or renamed since the link. Open the function list.'],
  backToList: ['الدوال', 'Functions'],
  allInFile: ['كل دوال هذا الملف ({n})', 'Every function of this file ({n})'],
  component: ['المكوّن', 'Component'],
  openOnMap: ['افتحه على الخريطة', 'Open it on the map'],
  signature: ['التوقيع', 'Signature'],
  noSignature: ['لم يُقرأ توقيعها', 'Its signature was not read'],
  lines: ['الأسطر', 'Lines'],
  complexity: ['التعقيد', 'Complexity'],
  calledBy: ['يستدعيها', 'Called by'],
  calls: ['تستدعي', 'Calls'],
  notMeasured: ['لم يُقس', 'not measured'],
  levelHigh: ['متشعبة جدًا: فوق حد التحذير {t}', 'Branches a lot: over the warning line of {t}'],
  levelWatch: ['تستحق الانتباه: قرب حد التحذير {t}', 'Worth watching: near the warning line of {t}'],
  levelOk: ['بسيطة', 'Simple'],
  source: ['المصدر', 'Source'],
  graph: ['من يستدعيها وما تستدعيه (خطوتان)', 'Who calls it and what it calls (two steps)'],
  graphAria: ['رسم الاستدعاءات حول {f}: {a} يستدعيها و{b} تستدعيها', 'Calls around {f}: {a} callers and {b} callees'],
  graphMore: ['و{n} غيرها في القوائم أدناه', 'and {n} more in the lists below'],
  graphFar: ['{n} أبعد بخطوتين لم تُرسم', '{n} further two-step neighbours not drawn'],
  graphNone: ['لا استدعاء تتبّعه EAOS من هذه الدالة أو إليها.', 'EAOS traced no call to or from this function.'],
  graphHint: ['اضغط مربعًا لتفتح تلك الدالة.', 'Press a box to open that function.'],
  graphTwo: ['يستدعي من يستدعيها', 'Calls its callers'],
  graphOne: ['يستدعيها', 'Calls it'],
  graphOut: ['تستدعيها', 'It calls'],
  graphOut2: ['تستدعيها هذه', 'Those call'],
  nobodyCalls: ['لا دالة في المشروع تستدعيها في الكود المقروء. قد يستدعيها إطار العمل أو ملف لم يُقرأ.', 'No function of the project calls it in the code read. A framework or a file not read may.'],
  callsNothing: ['لا تستدعي دالة أخرى من المشروع.', 'It calls no other function of the project.'],
  data: ['البيانات التي تلمسها', 'Data it touches'],
  reads: ['تقرأ', 'Reads'],
  writes: ['تكتب', 'Writes'],
  noData: ['لم يجد EAOS قراءة أو كتابة بيانات فيها.', 'EAOS found no data read or written in it.'],
  touch_table: ['جدول', 'table'],
  touch_file: ['ملف', 'file'],
  touch_env: ['متغير بيئة', 'environment variable'],
  touch_network: ['طلب شبكة', 'request'],
  touch_store: ['مخزن', 'store'],
  touch_storage: ['تخزين', 'storage'],
  problems: ['المشاكل عليها', 'Problems on it'],
  noProblems: ['لا مشكلة من الفحص على أسطرها.', 'No problem of the check sits on its lines.'],
  openRiskiest: ['افتح الأعقد بجوارها: {f}', 'Open its most complex neighbour: {f}'],
  openProblem: ['افتح المشكلة', 'Open the problem'],
  where: ['مكانها', 'Where it is'],
  linesOf: ['الأسطر {a}–{b}', 'lines {a}–{b}'],
  lineOf: ['السطر {a}', 'line {a}'],
  exported: ['مُصدَّرة من ملفها', 'Exported from its file'],
  internal: ['داخلية في ملفها', 'Internal to its file'],
  // the plain summary
  sumKind: ['{k} في {m}، طولها {l} سطرًا.', 'A {k} in {m}, {l} lines long.'],
  sumKindNoSize: ['{k} في {m}.', 'A {k} in {m}.'],
  sumCalls: ['تستدعيها {a} دالة، وتستدعي هي {b}.', '{a} functions call it, and it calls {b}.'],
  sumNoCallers: ['لا دالة في المشروع تستدعيها، وتستدعي هي {b}.', 'No function of the project calls it; it calls {b}.'],
  sumWrites: ['تكتب في: {w}.', 'It writes to: {w}.'],
  sumReads: ['تقرأ من: {r}.', 'It reads from: {r}.'],
  sumComplex: ['منطقها متشعب (تعقيد {c}، وحد التحذير {t}).', 'Its logic branches a lot (complexity {c}; the warning line is {t}).'],
} as const

export type FunctionWord = keyof typeof FUNCTION_WORDS
export const useFunctionWords = makeWords<FunctionWord>(FUNCTION_WORDS)
