// The words of the journeys map and the visible and hidden lens, Arabic first and English equally finished. A key
// missing in one language is a type error.
import { makeWords } from '../../map/words'

export const JOURNEY_WORDS = {
  // the system's views
  systemViews: ['خرائط النظام', 'System maps'],
  viewMap: ['البنية', 'Structure'],
  viewJourneys: ['رحلات المستخدم', 'User journeys'],
  viewHidden: ['الظاهر والخفي', 'Visible and hidden'],
  viewPaths: ['مسارات الكود', 'Code paths'],
  viewData: ['مسارات البيانات', 'Data paths'],
  viewInfra: ['البنية التحتية', 'Infrastructure'],
  viewPipeline: ['خط المعالجة', 'Pipeline'],
  viewFunctions: ['الدوال', 'Functions'],
  viewScreens: ['الشاشات', 'Screens'],
  // journeys: page and toolbar
  journeys: ['رحلات المستخدم', 'User journeys'],
  journeysLead: ['{s} شاشة يفتحها المستخدم، بينها {l} رابطًا، ومعها {t} مهمة مرسومة كمسار من البداية.', '{s} screens a person opens, {l} links between them, and {t} tasks drawn as paths from the start.'],
  journeysCount: ['{s} شاشة · {l} رابطًا · {t} مهمة', '{s} screens · {l} links · {t} tasks'],
  mapToday: ['اليوم', 'Today'],
  mapChange: ['التغيير', 'Change'],
  mapTarget: ['الهدف', 'Target'],
  mapView: ['ماذا تعرض الخريطة', 'What the map shows'],
  showAs: ['طريقة العرض', 'Show as'],
  asMap: ['خريطة', 'Map'],
  asSteps: ['خطوات', 'Steps'],
  showHidden: ['اعرض الخفي', 'Show hidden'],
  task: ['المهمة', 'Task'],
  noTask: ['كل الشاشات', 'Every screen'],
  chooseTask: ['اختر مهمة لترى طريقها', 'Choose a task to see its path'],
  problemsFilter: ['أبرز', 'Highlight'],
  // flags
  flag_broken_link: ['رابط مكسور', 'Broken link'],
  flag_no_way_in: ['لا رابط يوصل إليها', 'No way in'],
  flag_dead_end: ['طريق مسدود', 'Dead end'],
  flag_duplicate: ['شاشة مكررة', 'Duplicate'],
  flagWhy_broken_link: ['فيها رابط إلى مسار لا تفتحه أي شاشة.', 'It links to a path no screen opens.'],
  flagWhy_no_way_in: ['لا تصل إليها سلسلة روابط من البداية. قد يصلها المستخدم من بريد أو برابط خارجي فقط.', 'No chain of links reaches it from the start. A person may reach it only from an email or an outside link.'],
  flagWhy_dead_end: ['لا رابط فيها إلى شاشة أخرى، ولا قائمة.', 'It has no link to another screen, and no menu.'],
  flagWhy_duplicate: ['المسار نفسه معرّف مرتين، أو الملف نفسه على أكثر من مسار.', 'The same route is declared twice, or one file serves several routes.'],
  // kinds
  kind_page: ['شاشة', 'Screen'],
  kind_layout: ['تخطيط يغلّف شاشات', 'Layout around screens'],
  kind_redirect: ['تحويل تلقائي', 'Redirect'],
  kind_fallback: ['صفحة «غير موجود»', 'Not-found page'],
  menu: ['القائمة الجانبية والرأس', 'Menu and header'],
  menuSub: ['{n} رابطًا · تظهر على {s} شاشة', '{n} links · shown on {s} screens'],
  start: ['البداية', 'Start'],
  clicks: ['{n} نقرة من البداية', '{n} clicks from the start'],
  oneClick: ['نقرة واحدة من البداية', 'One click from the start'],
  noWayInCol: ['لا رابط يوصل إليها', 'No way in'],
  // legend
  legend: ['دليل الخريطة', 'Map legend'],
  lgScreen: ['شاشة يراها المستخدم', 'A screen the user sees'],
  lgHidden: ['يعمل ولا يُرى (نقش مائل)', 'Runs unseen (hatched)'],
  lgLink: ['رابط أو انتقال', 'Link or navigation'],
  lgRedirect: ['تحويل تلقائي', 'Redirect'],
  lgBroken: ['رابط مكسور', 'Broken link'],
  lgPath: ['طريق المهمة', 'The task’s path'],
  lgUndecided: ['؟ لا قرار للشاشة في الهدف', '? no decision for the screen in the target'],
  lgOpFolder: ['اللون: عملية مجلدها', 'Colour: its folder’s operation'],
  // inspector
  chooseScreen: ['اختر شاشة على الخريطة لترى روابطها ودليلها، أو اختر مهمة لترى طريقها.', 'Choose a screen on the map to see its links and evidence, or a task to see its path.'],
  route: ['المسار', 'Route'],
  file: ['الملف', 'File'],
  declaredAt: ['معرّفة في', 'Declared at'],
  declaredTwice: ['معرّفة {n} مرات', 'declared {n} times'],
  sameFile: ['الملف نفسه يخدم', 'The same file serves'],
  folder: ['مجلدها', 'Its folder'],
  folderOp: ['عملية مجلدها في الهدف', 'Its folder’s operation'],
  goesTo: ['يذهب إلى', 'goes to'],
  noScreenDecision: ['البنية المستهدفة تقرر المجلدات لا الشاشات: لا قرار لهذه الشاشة بعينها.', 'The target decides folders, not screens: this screen has no decision of its own.'],
  linksOut: ['روابط منها', 'Links out'],
  linksIn: ['روابط إليها', 'Links in'],
  brokenOut: ['روابط مكسورة منها', 'Broken links out'],
  noLinksOut: ['لا روابط منها', 'No links out'],
  noLinksIn: ['لا روابط إليها', 'No links in'],
  viaMenu: ['عبر القائمة', 'through the menu'],
  shots: ['صورة الشاشة', 'Screen shot'],
  noShot: ['لا صورة لها بعد: تصوير الشاشات يحتاج تشغيل التطبيق بموافقتك.', 'No shot yet: capturing screens needs the app running, with your agreement.'],
  unseenHere: ['ما يعمل خلفها ولا يُرى', 'What runs behind it, unseen'],
  tasksHere: ['مهام تمر بها', 'Tasks through it'],
  openFindings: ['افتح مشاكل مجلدها', 'Open its folder’s findings'],
  showOnMap: ['اعرضها على الخريطة', 'Show it on the map'],
  clusterSub: ['{s} شاشة', '{s} screens'],
  clusterFlags: ['{n} عليها ملاحظة', '{n} flagged'],
  areasHint: ['التطبيق كبير: الخريطة تعرض مناطقه. اختر منطقة لتفتح شاشاتها.', 'A large app: the map shows its areas. Choose an area to open its screens.'],
  allAreas: ['كل المناطق', 'All areas'],
  // tasks and steps
  tasks: ['المهام', 'Tasks'],
  steps: ['الخطوات', 'Steps'],
  stepStart: ['ابدأ من', 'Start at'],
  stepGo: ['انتقل إلى', 'Go to'],
  stepMenu: ['افتح القائمة', 'Open the menu'],
  stepDialog: ['افتح النافذة', 'Open the dialog'],
  stepVia: ['عبر', 'via'],
  taskNoPath: ['لا طريق من البداية إلى هذه المهمة: شاشتها لا يصلها رابط.', 'No path from the start reaches this task: no link leads to its screen.'],
  taskDead: ['ملفها في كود لا تعرضه أي شاشة (كود ميت).', 'Its file is in code no screen renders (dead code).'],
  taskFrom: ['من', 'from'],
  deadTasks: ['مهام في كود لا يُعرض', 'Tasks in code nobody sees'],
  byDepth: ['الشاشات بحسب بُعدها عن البداية', 'Screens by distance from the start'],
  // gaps and counts
  gaps: ['ما لم يُقس بعد', 'Not measured yet'],
  stepWord: ['الخطوة', 'Step'],
  unowned: ['روابط في كود لا تعرضه أي شاشة', 'Links in code no screen renders'],
  unownedDead: ['{n} منها في ملفات ميتة', '{n} of them in dead files'],
  relative: ['روابط نسبية لم تُربط', 'Relative links not resolved'],
  noJourneys: ['لا شاشات في هذا التقرير', 'This report has no screens'],
  noJourneysSub: ['الرحلات تُبنى من مسارات الواجهة التي يقرؤها EAOS (React Router وTanStack وNext.js). هذا المشروع بلا مسارات مقروءة، أو فُحص بنسخة أقدم.', 'Journeys are built from the front-end routes EAOS reads (React Router, TanStack, Next.js). This project has none it can read, or it was checked with an older EAOS.'],
  exploreMap: ['افتح الخريطة كاملة', 'Explore the full map'],
  closeMap: ['أغلق الخريطة', 'Close the map'],
  seeDetails: ['اعرض تفاصيلها', 'See its details'],
  mapAria: ['رحلات المستخدم: {s} شاشة و{l} رابطًا', 'User journeys: {s} screens and {l} links'],
  screenAria: ['{t}، المسار {r}{f}', '{t}, route {r}{f}'],
  evidence: ['الدليل', 'Evidence'],
  fact: ['الحقيقة', 'Fact'],
  card: ['البطاقة', 'Card'],
  more: ['و{n} أخرى', 'and {n} more'],
  // hidden
  hidden: ['الظاهر والخفي', 'Visible and hidden'],
  hiddenLead: ['{s} شاشة يراها المستخدم، ويعمل {u} شيئًا دون أن يُرى، منها {n} بلا أي شاشة أمامه.', '{s} screens the user sees, and {u} things that run unseen, {n} of them with no screen in front of them.'],
  seenSide: ['ما يراه المستخدم', 'What the user sees'],
  unseenSide: ['ما يعمل دون أن يُرى', 'What runs unseen'],
  area: ['منطقة', 'Area'],
  areaSub: ['{s} شاشة · {d} نافذة', '{s} screens · {d} dialogs'],
  public: ['الشاشات العامة', 'Public screens'],
  startArea: ['البداية', 'Start'],
  group_triggers: ['مهام خلفية ومُشغِّلات', 'Background jobs and triggers'],
  group_screens: ['مسارات ليست صفحات', 'Routes that are not pages'],
  group_server: ['مسارات الخادم', 'Server routes'],
  group_writes: ['كتابات تُرسل للبيانات', 'Writes sent to data'],
  group_outside: ['خدمات خارجية', 'Outside services'],
  group_config: ['إعدادات وأسرار', 'Configuration and secrets'],
  group_build: ['البناء والنشر', 'Build and deploy'],
  group_dead: ['كود ميت ومخلفات', 'Dead code and leftovers'],
  groupSub: ['{n} عنصرًا', '{n} items'],
  groupNone: ['لم يُوجد شيء', 'Nothing found'],
  noScreen: ['بلا شاشة أمامه', 'No screen in front'],
  noScreenWhy: ['يعمل أو ينتظر ولا شاشة يراها المستخدم تقوده.', 'It runs, or waits, with nothing the user sees in front of it.'],
  setsInMotion: ['تحرّكه هذه المناطق', 'Set in motion by'],
  itemsOf: ['عناصر «{g}»', 'Items of “{g}”'],
  linksFromArea: ['ما تحرّكه دون أن يُرى', 'What it sets in motion, unseen'],
  chooseSide: ['اختر منطقة أو مجموعة لترى عناصرها ودليل كل عنصر.', 'Choose an area or a group to see its items and the evidence of each.'],
  onlyNoScreen: ['ما لا شاشة أمامه فقط', 'Only what has no screen'],
  hiddenAria: ['الظاهر والخفي: {a} منطقة يراها المستخدم و{g} مجموعات تعمل دون أن تُرى', 'Visible and hidden: {a} areas the user sees and {g} groups that run unseen'],
  kindName: ['النوع', 'Kind'],
  noHidden: ['لا بيانات عن الخفي في هذا التقرير', 'This report has no data on what runs unseen'],
} satisfies Record<string, readonly [string, string]>

export type JourneyWord = keyof typeof JOURNEY_WORDS
export const useJourneyWords = makeWords<JourneyWord>(JOURNEY_WORDS)
